---
title: "abcd_ridge_prep"
output: html_document
date: "2022-12-16"
---

```{r}
# load in master longitudinal df
masterdf<-readRDS('~/OutDfFull.rds')
```

```{r}
library(mgcv)
library(ggplot2)
library(Metrics)

### predict tp2 internalizing


# subset into y1 and y2
masterdf1<-subset(masterdf,eventname=='baseline_year_1_arm_1')
masterdf2<-subset(masterdf,eventname=='2_year_follow_up_y_arm_1')
# tp2 tscore
outcomeofInt=masterdf2[c('subjectkey','cbcl_scr_syn_internal_t')]
# convert to numeric
outcomeofInt$cbcl_scr_syn_internal_t<-as.numeric(outcomeofInt$cbcl_scr_syn_internal_t)
# isolate df for scikitlearn: 1st column is outcome (internalizing TP2 t-score, rest of columns are features cog battery, cbcl)
# only subscale scores
subscaleScores<-colnames(masterdf)[grep('cbcl_scr_',colnames(masterdf))]
# only subscale raw scores
#subscaleRawScores<-subscaleScores[grep('_t',subscaleScores)]
# list cog vars
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","subjectkey","eventname")
predictorsofInt=c(pcVarsAndIDs,subscaleScores)
# remove eventname
predictorsofInt=predictorsofInt[-c(9)]
# manually adding two vars of int at end (internalizing and parent P)
predictorsofInt_y1<-masterdf1[,c(predictorsofInt,'cbcl_scr_syn_internal_t','parentPcount','g')]
# merge with outcome of interest
predictionDF=merge(predictorsofInt_y1,outcomeofInt,by='subjectkey')
# save only complete cases
predictionDF_comp=predictionDF[complete.cases(predictionDF),]
predictionDF_comp <- as.data.frame(lapply(predictionDF_comp, as.numeric))
# fit and predict on held-out sample
predObs_s=NULL
predObs_mae_s=NULL
tp1cor=NULL
tp1mae=NULL
# 80% of subjs is?
trainSize=round(dim(predictionDF_comp)[1]*.8)
testSize=dim(predictionDF_comp)[1]-trainSize
# k = 3 to prevent overfitting
k=3
# over 100 splits, fit on 80% of sample and test on 20%
for (s in 1:100){
  print(s)
  #train test indices
  trainTestInds=sample(1:dim(predictionDF_comp)[1])
  #training data is first "trainsize" samples
  trainDF=predictionDF_comp[trainTestInds[1:trainSize],]
  #testing data
  testDF=predictionDF_comp[trainTestInds[(trainSize+1):dim(predictionDF_comp)[1]],]
   # fit model on training data
  model=gam(cbcl_scr_syn_internal_t.y~s(cbcl_scr_07_ocd_t,k=k)+s(cbcl_scr_07_sct_t,k=k)+s(cbcl_scr_dsm5_conduct_t,k=k)+s(cbcl_scr_dsm5_opposit_t,k=k)+s(cbcl_scr_dsm5_adhd_t,k=k)+s(cbcl_scr_dsm5_somaticpr_t,k=k)+s(cbcl_scr_dsm5_anxdisord_t,k=k)+s(cbcl_scr_dsm5_depress_t,k=k)+s(cbcl_scr_syn_totprob_t,k=k)+s(cbcl_scr_syn_external_t,k=k)+s(cbcl_scr_syn_internal_t.x,k=k)+s(cbcl_scr_syn_aggressive_t,k=k)+s(cbcl_scr_syn_rulebreak_t,k=k)+s(cbcl_scr_syn_attention_t,k=k)+s(cbcl_scr_syn_thought_t,k=k)+s(cbcl_scr_syn_social_t,k=k)+s(cbcl_scr_syn_somatic_t,k=k)+s(cbcl_scr_syn_withdep_t,k=k)+s(cbcl_scr_syn_anxdep_t,k=k)+s(lmt_scr_perc_correct,k=k)+s(pea_ravlt_ld,k=k)+s(nihtbx_reading_uncorrected,k=k)+s(nihtbx_picture_uncorrected,k=k)+s(nihtbx_pattern_uncorrected,k=k)+s(nihtbx_flanker_uncorrected,k=k)+s(nihtbx_picvocab_uncorrected,k=k)+s(parentPcount,k=k),data=trainDF,select=TRUE)
  
  # test on test
  testDF$pred_tp2Int=predict.gam(model,testDF)
  predObs_s[s]=cor.test(testDF$cbcl_scr_syn_internal_t.y,testDF$pred_tp2Int)$estimate
  predObs_mae_s[s]=mae(testDF$cbcl_scr_syn_internal_t.y,testDF$pred_tp2Int)
  tp1cor[s]=cor.test(testDF$cbcl_scr_syn_internal_t.y,testDF$cbcl_scr_syn_internal_t.x)$estimate
  tp1mae[s]=mae(testDF$cbcl_scr_syn_internal_t.y,testDF$cbcl_scr_syn_internal_t.x)
}

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_s,tp1cor),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out correlations: Internal')

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_mae_s,tp1mae),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out M.A.E.: Internal')


```

```{r}
### predict tp2 externalizing


# subset into y1 and y2
masterdf1<-subset(masterdf,eventname=='baseline_year_1_arm_1')
masterdf2<-subset(masterdf,eventname=='2_year_follow_up_y_arm_1')
# tp2 tscore
outcomeofInt=masterdf2[c('subjectkey','cbcl_scr_syn_external_t')]
# convert to numeric
outcomeofInt$cbcl_scr_syn_external_t<-as.numeric(outcomeofInt$cbcl_scr_syn_external_t)
# isolate df for scikitlearn: 1st column is outcome (internalizing TP2 t-score, rest of columns are features cog battery, cbcl)
# only subscale scores
subscaleScores<-colnames(masterdf)[grep('cbcl_scr_',colnames(masterdf))]
# only subscale raw scores
#subscaleRawScores<-subscaleScores[grep('_t',subscaleScores)]
# list cog vars
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","subjectkey","eventname")
predictorsofInt=c(pcVarsAndIDs,subscaleScores)
# remove eventname
predictorsofInt=predictorsofInt[-c(9)]
# manually adding two vars of int at end (internalizing and parent P)
predictorsofInt_y1<-masterdf1[,c(predictorsofInt,'cbcl_scr_syn_external_t','parentPcount','g')]
# merge with outcome of interest
predictionDF=merge(predictorsofInt_y1,outcomeofInt,by='subjectkey')
# save only complete cases
predictionDF_comp=predictionDF[complete.cases(predictionDF),]
predictionDF_comp <- as.data.frame(lapply(predictionDF_comp, as.numeric))
# fit and predict on held-out sample
predObs_s=NULL
predObs_mae_s=NULL
tp1cor=NULL
tp1mae=NULL
# 80% of subjs is?
trainSize=round(dim(predictionDF_comp)[1]*.8)
testSize=dim(predictionDF_comp)[1]-trainSize
# k = 3 to prevent overfitting
k=3
# over 100 splits, fit on 80% of sample and test on 20%
for (s in 1:100){
  print(s)
  #train test indices
  trainTestInds=sample(1:dim(predictionDF_comp)[1])
  #training data is first "trainsize" samples
  trainDF=predictionDF_comp[trainTestInds[1:trainSize],]
  #testing data
  testDF=predictionDF_comp[trainTestInds[(trainSize+1):dim(predictionDF_comp)[1]],]
   # fit model on training data
  model=gam(cbcl_scr_syn_external_t.y~s(cbcl_scr_07_ocd_t,k=k)+s(cbcl_scr_07_sct_t,k=k)+s(cbcl_scr_dsm5_conduct_t,k=k)+s(cbcl_scr_dsm5_opposit_t,k=k)+s(cbcl_scr_dsm5_adhd_t,k=k)+s(cbcl_scr_dsm5_somaticpr_t,k=k)+s(cbcl_scr_dsm5_anxdisord_t,k=k)+s(cbcl_scr_dsm5_depress_t,k=k)+s(cbcl_scr_syn_totprob_t,k=k)+s(cbcl_scr_syn_external_t.x,k=k)+s(cbcl_scr_syn_internal_t,k=k)+s(cbcl_scr_syn_aggressive_t,k=k)+s(cbcl_scr_syn_rulebreak_t,k=k)+s(cbcl_scr_syn_attention_t,k=k)+s(cbcl_scr_syn_thought_t,k=k)+s(cbcl_scr_syn_social_t,k=k)+s(cbcl_scr_syn_somatic_t,k=k)+s(cbcl_scr_syn_withdep_t,k=k)+s(cbcl_scr_syn_anxdep_t,k=k)+s(lmt_scr_perc_correct,k=k)+s(pea_ravlt_ld,k=k)+s(nihtbx_reading_uncorrected,k=k)+s(nihtbx_picture_uncorrected,k=k)+s(nihtbx_pattern_uncorrected,k=k)+s(nihtbx_flanker_uncorrected,k=k)+s(nihtbx_picvocab_uncorrected,k=k)+s(parentPcount,k=k),data=trainDF,select=TRUE)
  
  # test on test
  testDF$pred_tp2Int=predict.gam(model,testDF)
  predObs_s[s]=cor.test(testDF$cbcl_scr_syn_external_t.y,testDF$pred_tp2Int)$estimate
  predObs_mae_s[s]=mae(testDF$cbcl_scr_syn_external_t.y,testDF$pred_tp2Int)
  tp1cor[s]=cor.test(testDF$cbcl_scr_syn_external_t.y,testDF$cbcl_scr_syn_external_t.x)$estimate
  tp1mae[s]=mae(testDF$cbcl_scr_syn_external_t.y,testDF$cbcl_scr_syn_external_t.x)
}

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_s,tp1cor),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out correlations: External')

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_mae_s,tp1mae),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out M.A.E.: External')


```

```{r}
# predict tp2 p


# subset into y1 and y2
masterdf1<-subset(masterdf,eventname=='baseline_year_1_arm_1')
masterdf2<-subset(masterdf,eventname=='2_year_follow_up_y_arm_1')
# tp2 tscore
outcomeofInt=masterdf2[c('subjectkey','cbcl_scr_syn_totprob_t')]
# convert to numeric
outcomeofInt$cbcl_scr_syn_totprob_t<-as.numeric(outcomeofInt$cbcl_scr_syn_totprob_t)
# isolate df for scikitlearn: 1st column is outcome (internalizing TP2 t-score, rest of columns are features cog battery, cbcl)
# only subscale scores
subscaleScores<-colnames(masterdf)[grep('cbcl_scr_',colnames(masterdf))]
# only subscale raw scores
#subscaleRawScores<-subscaleScores[grep('_t',subscaleScores)]
# list cog vars
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","subjectkey","eventname")
predictorsofInt=c(pcVarsAndIDs,subscaleScores)
# remove eventname
predictorsofInt=predictorsofInt[-c(9)]
# manually adding two vars of int at end (internalizing and parent P)
predictorsofInt_y1<-masterdf1[,c(predictorsofInt,'cbcl_scr_syn_totprob_t','parentPcount','g')]
# merge with outcome of interest
predictionDF=merge(predictorsofInt_y1,outcomeofInt,by='subjectkey')
# save only complete cases
predictionDF_comp=predictionDF[complete.cases(predictionDF),]
predictionDF_comp <- as.data.frame(lapply(predictionDF_comp, as.numeric))
# fit and predict on held-out sample
predObs_s=NULL
predObs_mae_s=NULL
tp1cor=NULL
tp1mae=NULL
# 80% of subjs is?
trainSize=round(dim(predictionDF_comp)[1]*.8)
testSize=dim(predictionDF_comp)[1]-trainSize
# k = 3 to prevent overfitting
k=3
# over 100 splits, fit on 80% of sample and test on 20%
for (s in 1:100){
  print(s)
  #train test indices
  trainTestInds=sample(1:dim(predictionDF_comp)[1])
  #training data is first "trainsize" samples
  trainDF=predictionDF_comp[trainTestInds[1:trainSize],]
  #testing data
  testDF=predictionDF_comp[trainTestInds[(trainSize+1):dim(predictionDF_comp)[1]],]
   # fit model on training data
  model=gam(cbcl_scr_syn_totprob_t.y~s(cbcl_scr_07_ocd_t,k=k)+s(cbcl_scr_07_sct_t,k=k)+s(cbcl_scr_dsm5_conduct_t,k=k)+s(cbcl_scr_dsm5_opposit_t,k=k)+s(cbcl_scr_dsm5_adhd_t,k=k)+s(cbcl_scr_dsm5_somaticpr_t,k=k)+s(cbcl_scr_dsm5_anxdisord_t,k=k)+s(cbcl_scr_dsm5_depress_t,k=k)+s(cbcl_scr_syn_totprob_t.x,k=k)+s(cbcl_scr_syn_external_t,k=k)+s(cbcl_scr_syn_internal_t,k=k)+s(cbcl_scr_syn_aggressive_t,k=k)+s(cbcl_scr_syn_rulebreak_t,k=k)+s(cbcl_scr_syn_attention_t,k=k)+s(cbcl_scr_syn_thought_t,k=k)+s(cbcl_scr_syn_social_t,k=k)+s(cbcl_scr_syn_somatic_t,k=k)+s(cbcl_scr_syn_withdep_t,k=k)+s(cbcl_scr_syn_anxdep_t,k=k)+s(lmt_scr_perc_correct,k=k)+s(pea_ravlt_ld,k=k)+s(nihtbx_reading_uncorrected,k=k)+s(nihtbx_picture_uncorrected,k=k)+s(nihtbx_pattern_uncorrected,k=k)+s(nihtbx_flanker_uncorrected,k=k)+s(nihtbx_picvocab_uncorrected,k=k)+s(parentPcount,k=k),data=trainDF,select=TRUE)
  
  # test on test
  testDF$pred_tp2Int=predict.gam(model,testDF)
  predObs_s[s]=cor.test(testDF$cbcl_scr_syn_totprob_t.y,testDF$pred_tp2Int)$estimate
  predObs_mae_s[s]=mae(testDF$cbcl_scr_syn_totprob_t.y,testDF$pred_tp2Int)
  tp1cor[s]=cor.test(testDF$cbcl_scr_syn_totprob_t.y,testDF$cbcl_scr_syn_totprob_t.x)$estimate
  tp1mae[s]=mae(testDF$cbcl_scr_syn_totprob_t.y,testDF$cbcl_scr_syn_totprob_t.x)
}

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_s,tp1cor),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out correlations: P')

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_mae_s,tp1mae),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out M.A.E.: P')

```


```{r}
# PREDICT DEPRESSION SCORE INSTEAD OF INTERNALIZING AGGREGATE

# subset into y1 and y2
masterdf1<-subset(masterdf,eventname=='baseline_year_1_arm_1')
masterdf2<-subset(masterdf,eventname=='2_year_follow_up_y_arm_1')
# tp2 tscore
outcomeofInt=masterdf2[c('subjectkey','cbcl_scr_dsm5_depress_t')]
# convert to numeric
outcomeofInt$cbcl_scr_dsm5_depress_t<-as.numeric(outcomeofInt$cbcl_scr_dsm5_depress_t)
# only subscale scores
subscaleScores<-colnames(masterdf)[grep('cbcl_scr_',colnames(masterdf))]
# only subscale raw scores
#subscaleRawScores<-subscaleScores[grep('_t',subscaleScores)]
# list cog vars
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","subjectkey","eventname")
predictorsofInt=c(pcVarsAndIDs,subscaleScores)
# remove eventname
predictorsofInt=predictorsofInt[-c(9)]
# manually adding two vars of int at end (internalizing and parent P)
predictorsofInt_y1<-masterdf1[,c(predictorsofInt,'cbcl_scr_dsm5_depress_t','parentPcount','g')]
# merge with outcome of interest
predictionDF=merge(predictorsofInt_y1,outcomeofInt,by='subjectkey')
# save only complete cases
predictionDF_comp=predictionDF[complete.cases(predictionDF),]
predictionDF_comp <- as.data.frame(lapply(predictionDF_comp, as.numeric))
# fit and predict on held-out sample
predObs_s=NULL
predObs_mae_s=NULL
# 80% of subjs is?
trainSize=round(dim(predictionDF_comp)[1]*.8)
testSize=dim(predictionDF_comp)[1]-trainSize
# k = 3 to prevent overfitting
k=3
# over 100 splits, fit on 80% of sample and test on 20%
for (s in 1:100){
  print(s)
  #train test indices
  trainTestInds=sample(1:dim(predictionDF_comp)[1])
  #training data is first "trainsize" samples
  trainDF=predictionDF_comp[trainTestInds[1:trainSize],]
  #testing data
  testDF=predictionDF_comp[trainTestInds[(trainSize+1):dim(predictionDF_comp)[1]],]
   # fit model on training data
  model=gam(cbcl_scr_dsm5_depress_t.y~s(cbcl_scr_07_ocd_t,k=k)+s(cbcl_scr_07_sct_t,k=k)+s(cbcl_scr_dsm5_conduct_t,k=k)+s(cbcl_scr_dsm5_opposit_t,k=k)+s(cbcl_scr_dsm5_adhd_t,k=k)+s(cbcl_scr_dsm5_somaticpr_t,k=k)+s(cbcl_scr_dsm5_anxdisord_t,k=k)+s(cbcl_scr_dsm5_depress_t.x,k=k)+s(cbcl_scr_syn_totprob_t,k=k)+s(cbcl_scr_syn_external_t,k=k)+s(cbcl_scr_syn_internal_t,k=k)+s(cbcl_scr_syn_aggressive_t,k=k)+s(cbcl_scr_syn_rulebreak_t,k=k)+s(cbcl_scr_syn_attention_t,k=k)+s(cbcl_scr_syn_thought_t,k=k)+s(cbcl_scr_syn_social_t,k=k)+s(cbcl_scr_syn_somatic_t,k=k)+s(cbcl_scr_syn_withdep_t,k=k)+s(cbcl_scr_syn_anxdep_t,k=k)+s(lmt_scr_perc_correct,k=k)+s(pea_ravlt_ld,k=k)+s(nihtbx_reading_uncorrected,k=k)+s(nihtbx_picture_uncorrected,k=k)+s(nihtbx_pattern_uncorrected,k=k)+s(nihtbx_flanker_uncorrected,k=k)+s(nihtbx_picvocab_uncorrected,k=k)+s(parentPcount,k=k),data=trainDF,select=TRUE)
  
  # test on test
  testDF$pred_tp2Int=predict.gam(model,testDF)
  predObs_s[s]=cor.test(testDF$cbcl_scr_dsm5_depress_t.y,testDF$pred_tp2Int)$estimate
  predObs_mae_s[s]=mae(testDF$cbcl_scr_dsm5_depress_t.y,testDF$pred_tp2Int)
  tp1cor[s]=cor.test(testDF$cbcl_scr_dsm5_depress_t.y,testDF$cbcl_scr_dsm5_depress_t.x)$estimate
  tp1mae[s]=mae(testDF$cbcl_scr_dsm5_depress_t.y,testDF$cbcl_scr_dsm5_depress_t.x)
}

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_s,tp1cor),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out correlations')

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_mae_s,tp1mae),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out M.A.E.')

```

```{r}
# tp2 tscore
outcomeofInt=masterdf2[c('subjectkey','cbcl_scr_dsm5_anxdisord_t')]
# convert to numeric
outcomeofInt$cbcl_scr_dsm5_anxdisord_t<-as.numeric(outcomeofInt$cbcl_scr_dsm5_anxdisord_t)
# only subscale scores
subscaleScores<-colnames(masterdf)[grep('cbcl_scr_',colnames(masterdf))]
# only subscale raw scores
#subscaleRawScores<-subscaleScores[grep('_t',subscaleScores)]
# list cog vars
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","subjectkey","eventname")
predictorsofInt=c(pcVarsAndIDs,subscaleScores)
# remove eventname
predictorsofInt=predictorsofInt[-c(9)]
# manually adding two vars of int at end (internalizing and parent P)
predictorsofInt_y1<-masterdf1[,c(predictorsofInt,'cbcl_scr_dsm5_anxdisord_t','parentPcount','g')]
# merge with outcome of interest
predictionDF=merge(predictorsofInt_y1,outcomeofInt,by='subjectkey')
# save only complete cases
predictionDF_comp=predictionDF[complete.cases(predictionDF),]
predictionDF_comp <- as.data.frame(lapply(predictionDF_comp, as.numeric))
# fit and predict on held-out sample
predObs_s=NULL
predObs_mae_s=NULL
# 80% of subjs is?
trainSize=round(dim(predictionDF_comp)[1]*.8)
testSize=dim(predictionDF_comp)[1]-trainSize
# k = 3 to prevent overfitting
k=3
# over 100 splits, fit on 80% of sample and test on 20%
for (s in 1:100){
  print(s)
  #train test indices
  trainTestInds=sample(1:dim(predictionDF_comp)[1])
  #training data is first "trainsize" samples
  trainDF=predictionDF_comp[trainTestInds[1:trainSize],]
  #testing data
  testDF=predictionDF_comp[trainTestInds[(trainSize+1):dim(predictionDF_comp)[1]],]
   # fit model on training data
  model=gam(cbcl_scr_dsm5_anxdisord_t.y~s(cbcl_scr_07_ocd_t,k=k)+s(cbcl_scr_07_sct_t,k=k)+s(cbcl_scr_dsm5_conduct_t,k=k)+s(cbcl_scr_dsm5_opposit_t,k=k)+s(cbcl_scr_dsm5_adhd_t,k=k)+s(cbcl_scr_dsm5_somaticpr_t,k=k)+s(cbcl_scr_dsm5_anxdisord_t.x,k=k)+s(cbcl_scr_dsm5_depress_t,k=k)+s(cbcl_scr_syn_totprob_t,k=k)+s(cbcl_scr_syn_external_t,k=k)+s(cbcl_scr_syn_internal_t,k=k)+s(cbcl_scr_syn_aggressive_t,k=k)+s(cbcl_scr_syn_rulebreak_t,k=k)+s(cbcl_scr_syn_attention_t,k=k)+s(cbcl_scr_syn_thought_t,k=k)+s(cbcl_scr_syn_social_t,k=k)+s(cbcl_scr_syn_somatic_t,k=k)+s(cbcl_scr_syn_withdep_t,k=k)+s(cbcl_scr_syn_anxdep_t,k=k)+s(lmt_scr_perc_correct,k=k)+s(pea_ravlt_ld,k=k)+s(nihtbx_reading_uncorrected,k=k)+s(nihtbx_picture_uncorrected,k=k)+s(nihtbx_pattern_uncorrected,k=k)+s(nihtbx_flanker_uncorrected,k=k)+s(nihtbx_picvocab_uncorrected,k=k)+s(parentPcount,k=k),data=trainDF,select=TRUE)
  
  # test on test
  testDF$pred_tp2Int=predict.gam(model,testDF)
  predObs_s[s]=cor.test(testDF$cbcl_scr_dsm5_anxdisord_t.y,testDF$pred_tp2Int)$estimate
  predObs_mae_s[s]=mae(testDF$cbcl_scr_dsm5_anxdisord_t.y,testDF$pred_tp2Int)
  tp1cor[s]=cor.test(testDF$cbcl_scr_dsm5_anxdisord_t.y,testDF$cbcl_scr_dsm5_anxdisord_t.x)$estimate
  tp1mae[s]=mae(testDF$cbcl_scr_dsm5_anxdisord_t.y,testDF$cbcl_scr_dsm5_anxdisord_t.x)
}

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_s,tp1cor),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out correlations')

# make a plot comparing distributions
dat <- data.frame(dens=c(predObs_mae_s,tp1mae),lines=rep(c("predicted","timepoint1Cor"),each=s))
# plot it
ggplot(dat, aes(x = dens, fill = lines)) + geom_density(alpha = 0.5)+ggtitle('Held-Out M.A.E.')
```

