library(mgcv)
masterdf=readRDS('/oak/stanford/groups/leanew1/users/apines/data/gp/mixedEfDf.rds')
gpAge<-gam(cbcl_scr_syn_totprob_r~s(g)+s(interview_age)+s(subjectkey,bs='re'),data=masterdf,family=nb())
gpAge_te<-gam(cbcl_scr_syn_totprob_r~te(g,interview_age)+s(subjectkey,bs='re'),data=masterdf,family=nb())
#saveRDS(gpAge_te,'~/gpAge_te.rds')
#saveRDS(gpAge,'~/gpAge.rds')
# resilient version
rdata_file = file("/oak/stanford/groups/leanew1/users/apines/data/gp/gpAge_te.rds", blocking = TRUE)
saveRDS(gpAge_te, file=rdata_file)
close(rdata_file)
rdata_file = file("/oak/stanford/groups/leanew1/users/apines/data/gp/apines/gpAge.rds", blocking = TRUE)
saveRDS(gpAge, file=rdata_file)
close(rdata_file)
