---
title: "Ispot"
output: html_document
date: "2023-06-05"
---

```{r}
library(mice)
library(ggplot2)
library(mgcv)
# load in data
data=read.csv('~/Downloads/PanLabMergedDatabase-Ispotdin_DATA_2023-04-25_1418.csv')

bl=data[data$redcap_event_name %in% c('baseline_arm_1', 'baseline_arm_2'), ]

# to sep. out HCs
#bl=bl[bl$mdd_current==0, ]

p_feats=c('qids_01', 'qids_02', 'qids_03', 'qids_04', 'qids_05', 'qids_06', 'qids_07', 'qids_08', 'qids_09', 'qids_10', 'qids_11', 'qids_12', 'qids_13', 'qids_14', 'qids_15', 'qids_16', 'hdrs21_01', 'hdrs21_02', 'hdrs21_03', 'hdrs21_04', 'hdrs21_05', 'hdrs21_06', 'hdrs21_07', 'hdrs21_08', 'hdrs21_09', 'hdrs21_10', 'hdrs21_11', 'hdrs21_12', 'hdrs21_13', 'hdrs21_14', 'hdrs21_15', 'hdrs21_16', 'hdrs21_17', 'hdrs21_18', 'hdrs21_19', 'hdrs21_20', 'hdrs21_21', 'dass42_01', 'dass42_02', 'dass42_03', 'dass42_04', 'dass42_05', 'dass42_06', 'dass42_07', 'dass42_08', 'dass42_09', 'dass42_10', 'dass42_11', 'dass42_12', 'dass42_13', 'dass42_14', 'dass42_15', 'dass42_16', 'dass42_17', 'dass42_18', 'dass42_19', 'dass42_20', 'dass42_21', 'dass42_22', 'dass42_23', 'dass42_24', 'dass42_25', 'dass42_26', 'dass42_27', 'dass42_28', 'dass42_29', 'dass42_30', 'dass42_31', 'dass42_32', 'dass42_33', 'dass42_34', 'dass42_35', 'dass42_36', 'dass42_37', 'dass42_38', 'dass42_39', 'dass42_40', 'dass42_41', 'dass42_42')
g_feats=grep(pattern = '_norm', names(bl), value = T)

### to impute
# Filter out subjects with >80% of items present
bl_filtered <- bl[rowSums(is.na(bl[p_feats]))/length(p_feats) <= 0.2, ]
ids=bl_filtered$id
# Perform imputation using mice package
imputed_data <- mice(bl_filtered[, p_feats])
#### PCA FOR p ####
# Extract completed datasets
completed_data <- imputed_data$data
completed_data$id<-ids
completed_data=na.omit(completed_data[, c('id', p_feats)])
# temp df for merging back
temp=data.frame(completed_data$id)
colnames(temp)='id'
# Perform PCA on the imputed data
pca_result <- prcomp(completed_data[, p_feats])

# Create a scree plot
# Extract the proportion of variance explained by each principal component
explained_variance_ratio <- pca_result$sdev^2 / sum(pca_result$sdev^2)
# Create a data frame with the explained variance ratio
explained_variance_df <- data.frame(
  PC = factor(1:length(explained_variance_ratio)),
  ExplainedVarianceRatio = explained_variance_ratio
)
# Create a scree plot
scree_plot <- ggplot(explained_variance_df, aes(x = PC, y = ExplainedVarianceRatio)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "Scree Plot",
       x = "Principal Component",
       y = "Proportion of Variance Explained")
# Display the scree plot
print(scree_plot)

```


```{r}
# Extract the loadings from the PCA result and map back to dataframe
temp$p_pc1=pca_result$x[, 1]
bl_filtered=merge(temp[, c('id','p_pc1')], bl_filtered, all = T)
```

```{r}
#### PCA FOR g ####
temp=na.omit(bl_filtered[, c('id', g_feats)])

# Filter out subjects with >80% of items present
bl_filtered2 <- bl_filtered[rowSums(is.na(bl_filtered[g_feats]))/length(g_feats) <= 0.2, ]
ids=bl_filtered2$id
# Perform imputation using mice package
imputed_data <- mice(bl_filtered2[, g_feats])
#### PCA FOR p ####
# Extract completed datasets
completed_data <- imputed_data$data
completed_data$id<-ids
completed_data=na.omit(completed_data[, c('id', g_feats)])
# temp df for merging back
temp=data.frame(completed_data$id)
colnames(temp)='id'
# Perform PCA on the imputed data
pca_result <- prcomp(completed_data[, g_feats])

# Create a scree plot
# Extract the proportion of variance explained by each principal component
explained_variance_ratio <- pca_result$sdev^2 / sum(pca_result$sdev^2)
# Create a data frame with the explained variance ratio
explained_variance_df <- data.frame(
  PC = factor(1:length(explained_variance_ratio)),
  ExplainedVarianceRatio = explained_variance_ratio
)
# Create a scree plot
scree_plot <- ggplot(explained_variance_df, aes(x = PC, y = ExplainedVarianceRatio)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "Scree Plot",
       x = "Principal Component",
       y = "Proportion of Variance Explained")
# Display the scree plot
print(scree_plot)

# Step 1: Extract the loadings from the PCA result and map back to dataframe
temp$g_pc1=pca_result$x[, 1]
bl_filtered3=merge(temp[, c('id','g_pc1')], bl_filtered2, all = T)
bl_filtered4=bl_filtered3[bl_filtered3$mdd_current==0,]
```

```{r}
# why is there huge age effect?
model<-gam(g_pc1~s(p_pc1)+s(age),data=bl_filtered3)

visreg(model,"q_pc1",gg=TRUE,ylab="g",xlab="p",line.par=list(size=2,col='black'),alpha=0.05)+theme_minimal(base_size=25)
get_derivs_and_plot(model,smooth_var="g_pc1")

# now for each sex
bl1<-bl[bl$gender==1,]
model<-gam(b_pc1~s(q_pc1,k=4),data=bl1)
get_derivs_and_plot(model,smooth_var="q_pc1")
visreg(model,"q_pc1",gg=TRUE,ylab="g",xlab="p",line.par=list(size=2,col='black'),alpha=0.05)+theme_minimal(base_size=25)

bl2<-bl[bl$gender==2,]
model<-gam(b_pc1~s(q_pc1,k=4),data=bl2)
get_derivs_and_plot(model,smooth_var="q_pc1")
visreg(model,"q_pc1",gg=TRUE,ylab="g",xlab="p",line.par=list(size=2,col='black'),alpha=0.05)+theme_minimal(base_size=25)
```