---
title: "SampleConstruction"
author: "Adam"
output: github_document
date: "2023-01-25"
---

This .rmd links ndar downloads into a master dataset. Cross-sectional and temporal precedence datasets are be exported from this file (no matched imaging groups needed, pooled factor decomposition).

```{r}
#### load libraries
library(rapportools)
library(reshape2)
library(ggplot2)
library(ggalluvial)

### TO DO's
# check for less missingness in newer packages
# adapt lancP version for pov/nonpov interactions based on #-in-household-specific poverty lines
# ensure parent-child discrep not unequal by pov
# relegate sex effects to supp
# add in polynomials
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
####  chunk 1 processes mental health data  ####
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

### LOAD in cbcl data
cbcl=read.csv('~/Downloads/abcd-data-release-5.1/core/mental-health/mh_p_cbcl.csv')
# subset timepoints
cbclBV=subset(cbcl,eventname=='baseline_year_1_arm_1')
cbcl2=subset(cbcl,eventname=='2_year_follow_up_y_arm_1')

# initialize master df
masterdf<-cbcl

# omit nans and empties for variables of interest (totprobs,int,ext)
masterdf=masterdf[!is.empty(masterdf$cbcl_scr_syn_totprob_r),]
masterdf=masterdf[!is.na(masterdf$cbcl_scr_syn_totprob_r),]
masterdf=masterdf[!is.empty(masterdf$cbcl_scr_syn_internal_r),]
masterdf=masterdf[!is.na(masterdf$cbcl_scr_syn_internal_r),]
masterdf=masterdf[!is.empty(masterdf$cbcl_scr_syn_external_r),]
masterdf=masterdf[!is.na(masterdf$cbcl_scr_syn_external_r),]

# initialize included subjects df
includedSubjects=data.frame(unique(masterdf$src_subject_id))
colnames(includedSubjects)<-'subj'
includedSubjects$cbclInclude=1

# check for completeness at both timepoints- subset those timepoints
masterdf=masterdf[masterdf$eventname!='1_year_follow_up_y_arm_1',]
masterdf=masterdf[masterdf$eventname!='3_year_follow_up_y_arm_1',]
# calculate remaining subjs
cbclSubjs=length(unique(masterdf$src_subject_id))
length(unique(masterdf$src_subject_id))

# get other vars of interest to check for complete cases
KidVarsOfInt=c('cbcl_scr_syn_totprob_r','cbcl_scr_syn_external_r','cbcl_scr_syn_internal_r')

# only use subjects with both timepoints as complete cases
subjs=unique(masterdf$src_subject_id)
for (s in subjs){
  # if there are less than two complete cases of the variables of interest
  if (sum(complete.cases(masterdf[masterdf$src_subject_id==s,c(KidVarsOfInt)]))<2){
    subjs=subjs[subjs!=s]
  }
}

# exclude participants without data at both timepoints
cbclSubjs=length(unique(masterdf$src_subject_id))
masterdf=masterdf[masterdf$src_subject_id %in% subjs,]

# included subjs df
includedSubjects$CBCLBoth=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$CBCLBoth=1

cbclSubjsBoth=length(unique(masterdf$src_subject_id))
print(paste0(cbclSubjs-cbclSubjsBoth,' lost due to single-timepoint CBCL completeness'))
```
```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
###   Chunk 2  processes  scholastic  data.  ###
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

### LOAD in grades, ∆∆∆ will need to correct for incongruency between tp1 measure (decent granularity) and tp2 measure (high granularity) ∆∆∆
gradesInfoBV=read.csv('~/Downloads/abcd-data-release-5.1/core/mental-health/mh_p_ksads_bg.csv')
# extract baseline
gradesInfoBV=subset(gradesInfoBV,eventname=='baseline_year_1_arm_1')
gradesInfoBV$Grades<-as.numeric(gradesInfoBV$kbi_p_grades_in_school)
# convert ndar value to R
gradesInfoBV$Grades[gradesInfoBV$Grades==-1]=NA
# ungraded NA for these analyses
gradesInfoBV$Grades[gradesInfoBV$Grades==6]=NA
# convert ndar colnames to other ndar colnames
# for tp2, the key is 1 = A's, 2 = B's, 3 = C's, 4 = D's, 5 = F's, 6 = ungraded, -1 = NA
gradesInfoY2=read.csv('~/Downloads/abcd-data-release-5.1/core/culture-environment/ce_p_sag.csv')
gradesInfoY2=subset(gradesInfoY2,eventname=='2_year_follow_up_y_arm_1')
gradesInfoY2$sag_grade_type<-as.numeric(gradesInfoY2$sag_grade_type)
# key: 1=100-97,2=96-93,3=92-90,4=89-87,5=86-83,6=82-80,7=79-77,8=76-73,9=72-70,10=69-67,11=66-65,12=0-65,-1=NA,777= no answer
gradesInfoY2$sag_grade_type[gradesInfoY2$sag_grade_type==-1]=NA
gradesInfoY2$sag_grade_type[gradesInfoY2$sag_grade_type==777]=NA
# now convert to be equivalent with timepoint 1 grades measure
ind12=gradesInfoY2$sag_grade_type==12
ind11=gradesInfoY2$sag_grade_type==11
ind10=gradesInfoY2$sag_grade_type==10
ind9=gradesInfoY2$sag_grade_type==9
ind8=gradesInfoY2$sag_grade_type==8
ind7=gradesInfoY2$sag_grade_type==7
ind6=gradesInfoY2$sag_grade_type==6
ind5=gradesInfoY2$sag_grade_type==5
ind4=gradesInfoY2$sag_grade_type==4
ind3=gradesInfoY2$sag_grade_type==3
ind2=gradesInfoY2$sag_grade_type==2
ind1=gradesInfoY2$sag_grade_type==1
#### Set indices to low-res versions
# < 65 becomes failing
gradesInfoY2$sag_grade_type[ind12]=5
# 66-69 = Ds
gradesInfoY2$sag_grade_type[ind11]=4
gradesInfoY2$sag_grade_type[ind10]=4
# 70-79 = Cs
gradesInfoY2$sag_grade_type[ind7]=3
gradesInfoY2$sag_grade_type[ind8]=3
gradesInfoY2$sag_grade_type[ind9]=3
# 80-89 = Bs
gradesInfoY2$sag_grade_type[ind4]=2
gradesInfoY2$sag_grade_type[ind5]=2
gradesInfoY2$sag_grade_type[ind6]=2
# 90+ = As
gradesInfoY2$sag_grade_type[ind1]=1
gradesInfoY2$sag_grade_type[ind2]=1
gradesInfoY2$sag_grade_type[ind3]=1
gradesInfoY2$Grades<-gradesInfoY2$sag_grade_type

###### ∆∆∆∆∆∆∆ create grades info from both of em
NeededColNames=c('src_subject_id','eventname','Grades')
gradesInfo<-rbind(gradesInfoBV[,NeededColNames],gradesInfoY2[,NeededColNames])
gradesInfo$Grades<-as.ordered(gradesInfo$Grades)

# merge and count losses
masterdf<-merge(masterdf,gradesInfo,by=c('src_subject_id','eventname'))

# subjects with this measure at both timepoints
# only use subjects with both timepoints as complete cases
subjs=unique(masterdf$src_subject_id)
for (s in subjs){
  # if there are less than two complete cases of the variables of interest
  if (sum(complete.cases(masterdf[masterdf$src_subject_id==s,'Grades']))<2){
    subjs=subjs[subjs!=s]
  }
}

# exclude participants without data at both timepoints
masterdf=masterdf[masterdf$src_subject_id %in% subjs,]

# omit nans and empties for variables of interest (totprobs,int,ext)
masterdf=masterdf[!is.empty(masterdf$Grades),]
masterdf=masterdf[!is.na(masterdf$Grades),]
gradesSubjs=length(unique(masterdf$src_subject_id))
# add to included subjs DF
includedSubjects$Grades=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$Grades=1
# print data volume
print(gradesSubjs)
dif=cbclSubjsBoth-gradesSubjs
print(paste0(dif,' participants lost from grades merge'))

# included subjs df
includedSubjects$Grades=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$Grades=1

```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
#### Chunk 3 processes adult mental health ####
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

### LOAD in ASR data
asr=read.delim('~/Downloads/Package_1210940/pasr01.txt',na.strings=c("","NA"))
# merge
masterdf<-merge(masterdf,asr,by=c('src_subject_id','eventname','interview_age','sex'))
# check for populated data at BOTH timepoints
ColsOfInt=asr[,c(11:141)]
ASRVarsOfInt=colnames(ColsOfInt)
# only use subjects with both timepoints as complete cases
subjs=unique(masterdf$src_subject_id)
for (s in subjs){
  # if there are less than two complete cases of the variables of interest
  if (sum(complete.cases(masterdf[masterdf$src_subject_id==s,c(ASRVarsOfInt)]))<2){
    subjs=subjs[subjs!=s]
  }
}

masterdf=masterdf[masterdf$src_subject_id %in% subjs,]

# full losses counted after asr count chunk, but note one participant is probably lost here just from merge
asrSubjs=length(unique(masterdf$src_subject_id))
dif=gradesSubjs-asrSubjs
print(paste0(dif,' participants lost from needing ASR at both timepoints'))

# included subjs df
includedSubjects$ASR=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$ASR=1
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
####  Chunk 4   processes family ID   data  ####
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# load in acs file for rel_family_ID
# get family ID from acs
acs=read.delim('~/Downloads/Package_1210940/acspsw03.txt')
acs$src_subject_id<-acs$src_subject_id
acs=acs[,c('rel_family_id','src_subject_id','eventname')]
# looks like all family IDs are missing from timepoint 1, so exclude for ease
acs=acs[acs$eventname=='baseline_year_1_arm_1',]
# and isolate family ID for ease
acs=data.frame(acs$src_subject_id,acs$rel_family_id)
colnames(acs)=c('src_subject_id','rel_family_id')
masterdf<-merge(masterdf,acs,by=c('src_subject_id'))
# na omitted version
masterdf=masterdf[!is.na(masterdf$rel_family_id),] 
masterdf=masterdf[!is.empty(masterdf$rel_family_id),] 
acsSubjs=length(unique(masterdf$src_subject_id))
# add to included subjs DF
includedSubjects$acs=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$acs=1
# print data volume
print(acsSubjs)
dif=asrSubjs-acsSubjs
print(paste0(dif,' participants lost from ACS merge for family ID'))
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
### This  (short)  chunk formats   cbcl data ###
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

### CLEAN data
# src_subject_id as factor
masterdf$src_subject_id<-as.factor(masterdf$src_subject_id)
# convert cbcl scores to numeric
masterdf$cbcl_scr_syn_totprob_r<-as.numeric(masterdf$cbcl_scr_syn_totprob_r)
masterdf$cbcl_scr_syn_internal_r<-as.numeric(masterdf$cbcl_scr_syn_internal_r)
masterdf$cbcl_scr_syn_external_r<-as.numeric(masterdf$cbcl_scr_syn_external_r)

```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
####   Chunk 6 processes cognitive data    ####
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

#### LOAD in cognitive data
nihCog=read.delim('~/Downloads/Package_1210940/abcd_tbss01.txt')
othCog=read.delim('~/Downloads/Package_1210940/abcd_ps01.txt')
littleMan=read.delim('~/Downloads/Package_1210940/lmtp201.txt')

# merge in
masterdf<-merge(masterdf,nihCog,by=c('src_subject_id','eventname','interview_age','sex'))
newList=length(unique(masterdf$src_subject_id))
print(paste0(newList,' after merging nih toolbox, ',(acsSubjs- newList),' lost after merge'))
masterdf<-merge(masterdf,othCog,by=c('src_subject_id','eventname','interview_age','sex'))
newList2=length(unique(masterdf$src_subject_id))
print(paste0(newList2,' after merging other cognitive measures, ',(newList- newList2),' lost after merge'))
masterdf<-merge(masterdf,littleMan,by=c('src_subject_id','eventname','interview_age','sex'))
newList3=length(unique(masterdf$src_subject_id))
print(paste0(newList3,' after merging little man, ',(newList2 - newList3),' lost after merge'))

# clean age
masterdf$interview_age<-as.numeric(masterdf$interview_age)
masterdf$interview_age<-as.numeric(masterdf$interview_age)/12
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
## Chunk 7 preps for cognition factorization ###
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# use thompson 2019 recreation of non nih-tb measures
ind_pea_ravlt = c(which(names(masterdf)=="pea_ravlt_sd_trial_i_tc"),which(names(masterdf)=="pea_ravlt_sd_trial_ii_tc"),
	which(names(masterdf)=="pea_ravlt_sd_trial_iii_tc"),which(names(masterdf)=="pea_ravlt_sd_trial_iv_tc"),
	which(names(masterdf)=="pea_ravlt_sd_trial_v_tc")); names(masterdf)[ind_pea_ravlt];

# set numbers to numeric
masterdf$pea_ravlt_sd_trial_i_tc=as.numeric(masterdf$pea_ravlt_sd_trial_i_tc)
masterdf$pea_ravlt_sd_trial_ii_tc=as.numeric(masterdf$pea_ravlt_sd_trial_ii_tc)
masterdf$pea_ravlt_sd_trial_iii_tc=as.numeric(masterdf$pea_ravlt_sd_trial_iii_tc)
masterdf$pea_ravlt_sd_trial_iv_tc=as.numeric(masterdf$pea_ravlt_sd_trial_vi_tc)
masterdf$pea_ravlt_sd_trial_v_tc=as.numeric(masterdf$pea_ravlt_sd_trial_v_tc)

# total correct across trials
masterdf$pea_ravlt_ld = masterdf$pea_ravlt_sd_trial_i_tc + masterdf$pea_ravlt_sd_trial_ii_tc + masterdf$pea_ravlt_sd_trial_iii_tc + masterdf$pea_ravlt_sd_trial_iv_tc + masterdf$pea_ravlt_sd_trial_v_tc

# change to numeric
masterdf$nihtbx_picvocab_uncorrected<-as.numeric(masterdf$nihtbx_picvocab_uncorrected)
masterdf$nihtbx_flanker_uncorrected<-as.numeric(masterdf$nihtbx_flanker_uncorrected)
masterdf$nihtbx_list_uncorrected<-as.numeric(masterdf$nihtbx_list_uncorrected)
masterdf$nihtbx_cardsort_uncorrected<-as.numeric(masterdf$nihtbx_cardsort_uncorrected)
masterdf$nihtbx_pattern_uncorrected<-as.numeric(masterdf$nihtbx_pattern_uncorrected)
masterdf$nihtbx_picture_uncorrected<-as.numeric(masterdf$nihtbx_picture_uncorrected)
masterdf$nihtbx_reading_uncorrected<-as.numeric(masterdf$nihtbx_reading_uncorrected)
masterdf$pea_wiscv_tss<-as.numeric(masterdf$pea_wiscv_tss)
masterdf$lmt_scr_perc_correct<-as.numeric(masterdf$lmt_scr_perc_correct)

# for isolating PCA dataframe
pcVars=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct")

# only use subjects with both timepoints as complete cases
subjs=unique(masterdf$src_subject_id)
for (s in subjs){
  # if there are less than two complete cases of the variables of interest
  if (sum(complete.cases(masterdf[masterdf$src_subject_id==s,c(pcVars)]))<2){
    subjs=subjs[subjs!=s]
  }
}
# convert masterdf to df with complete observations for cognition
masterdf=masterdf[masterdf$src_subject_id %in% subjs,]
newList4=length(unique(masterdf$src_subject_id))
print(paste0(newList4,' after retaining only subjs with Cognitive vars of interest at BOTH timepoints, ',(newList3- newList4),' lost after removing'))

# populated included subjs df
includedSubjects$CogBoth=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$CogBoth=1
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
###  Chunk 8 preps by selecting 1 per family ###
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
# finish cleaning data for sherlock runs: one family member per family to facilitate random sample
masterdf$id_fam = NULL
# default value of family size (# of children in abcd study)
masterdf$fam_size = 1

# counter index
ind=0

# set each instance of multiple family members to a family ID, as ind
set.seed(1)
for(f in 1:length(unique(masterdf$rel_family_id))){
  # calculate family size
  famsize=sum(masterdf$rel_family_id == unique(masterdf$rel_family_id)[f]) / 2
  masterdf$fam_size[masterdf$rel_family_id == unique(masterdf$rel_family_id)[f]] = famsize
  # note that each  person is represented twice at this point:
  # divide by 2 to take number of visits to number of people, if there's more than 2x visits per family ID, izza family
  # this logic gets hairy. Starting from outside in: > 1 is family size >1, /2 is divided by 2 for two visits, [f] is unique familyID, rel_family_id is place in column of masterdf
  if(famsize>1){
    # remove one from instances where family-id = this relative family id (sequence for siblings, 1:size(Family))
    #print(paste0('family size ',famsize))
    # keep one sib
    kept=sample(seq(1,famsize),1)
    #print(paste0('kept ',kept))
    # use to select one subject id
    famIDs=unique(masterdf$src_subject_id[masterdf$rel_family_id == unique(masterdf$rel_family_id)[f]])
    # chosen sib
    keeper=famIDs[kept]
    left=famIDs[-c(kept)]
    # leave rest
    masterdf=masterdf[!masterdf$src_subject_id %in% left,] 
    # calc index of family
    ind=ind+1	
    # set index of family
    masterdf$id_fam[masterdf$rel_family_id == unique(masterdf$rel_family_id)[f]] = ind
  }	
}

# make family ID for those with families represented in ABCD
masterdf$rel_family_id=masterdf$id_fam

newList5=length(unique(masterdf$src_subject_id))
print(paste0(newList5,' after retaining only one subjs per family, ',(newList4- newList5),' lost after removing'))

# included subjects DF to track subj loss
includedSubjects$OnePerFamily=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$OnePerFamily=1

# pea_wiscv_tss, nihtbx_list_uncorrected, and nihtbx_cardsort_uncorrected taken out for lack of longitudinal coverage
pcaDf<-masterdf[,pcVars]
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
### Chunk 9: it runs cognition factorization ###
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# derive pcs
Y = as.matrix(scale(pcaDf[complete.cases(pcaDf[,pcVars]),pcVars]))
# equiv for binding scores to IDs and eventnames
pcVarsAndIDs=c("nihtbx_picvocab_uncorrected","nihtbx_flanker_uncorrected","nihtbx_pattern_uncorrected","nihtbx_picture_uncorrected","nihtbx_reading_uncorrected","pea_ravlt_ld","lmt_scr_perc_correct","src_subject_id","eventname")
Yextended=masterdf[complete.cases(masterdf[,pcVarsAndIDs]),pcVarsAndIDs]
ncomp = 3
y.pca = psych::principal(Y, rotate="varimax", nfactors=ncomp, scores=TRUE)
y.pca$loadings
# assign scores to subjs
Yextended$g<-y.pca$scores[,1]

# merge in cog data
masterdf$g<-Yextended$g
```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
## Chunk 10 subjects with data at both timepoints##
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# exclude subjs without data for both timepoints
OutDFsubjects=length(unique(masterdf$src_subject_id))
OutDFBV=subset(masterdf,eventname=='baseline_year_1_arm_1')
OutDF2Y=subset(masterdf,eventname=='2_year_follow_up_y_arm_1')
# intersection of subjs in both
BothTPsubjs=intersect(OutDFBV$src_subject_id,OutDF2Y$src_subject_id)
Different=setdiff(unique(masterdf$src_subject_id),BothTPsubjs)
# print sanity check subjs lost to another check of both tps populated
newList6=length(unique(BothTPsubjs))
dif=newList5-newList6
print(paste0(dif,' rows lost from only using subjs with both timepoints'))

```

```{r}

###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
## Chunk 11 calculates adult mental health    ##
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
# make count version of adult P
ASRdfNum<-as.data.frame(lapply(asr[-1,11:141],as.numeric))
ASRtotal=rowSums(ASRdfNum)

ASRAnxDepr=ASRdfNum$asr_q12_p+ASRdfNum$asr_q13_p+ASRdfNum$asr_q14_p+ASRdfNum$asr_q22_p+ASRdfNum$asr_q31_p+ASRdfNum$asr_q33_p+ASRdfNum$asr_q34_p+ASRdfNum$asr_q35_p+ASRdfNum$asr_q45_p+ASRdfNum$asr_q47_p+ASRdfNum$asr_q50_p+ASRdfNum$asr_q71_p+ASRdfNum$asr_q91_p+ASRdfNum$asr_q103_p+ASRdfNum$asr_q107_p+ASRdfNum$asr_q112_p+ASRdfNum$asr_q113_p

ASRWithdrawn=ASRdfNum$asr_q25_p+ASRdfNum$asr_q30_p+ASRdfNum$asr_q42_p+ASRdfNum$asr_q48_p+ASRdfNum$asr_q60_p+ASRdfNum$asr_q65_p+ASRdfNum$asr_q67_p+ASRdfNum$asr_q69_p+ASRdfNum$asr_q111_p

ASRSomatic=ASRdfNum$asr_q51_p+ASRdfNum$asr_q56a_p+ASRdfNum$asr_q56b_p+ASRdfNum$asr_q56c_p+ASRdfNum$asr_q56e_p+ASRdfNum$asr_q56f_p+ASRdfNum$asr_q56g_p+ASRdfNum$asr_q56h_p+ASRdfNum$asr_q56i_p+ASRdfNum$asr_q100_p

ASRThought=ASRdfNum$asr_q09_p+ASRdfNum$asr_q18_p+ASRdfNum$asr_q36_p+ASRdfNum$asr_q40_p+ASRdfNum$asr_q46_p+ASRdfNum$asr_q63_p+ASRdfNum$asr_q66_p+ASRdfNum$asr_q70_p+ASRdfNum$asr_q80_p+ASRdfNum$asr_q84_p+ASRdfNum$asr_q85_p+ASRdfNum$asr_q91_p

ASRAttn=ASRdfNum$asr_q01_p+ASRdfNum$asr_q08_p+ASRdfNum$asr_q11_p+ASRdfNum$asr_q13_p+ASRdfNum$asr_q17_p+ASRdfNum$asr_q53_p+ASRdfNum$asr_q59_p+ASRdfNum$asr_q61_p+ASRdfNum$asr_q64_p+ASRdfNum$asr_q78_p+ASRdfNum$asr_q96_p+ASRdfNum$asr_q101_p+ASRdfNum$asr_q102_p+ASRdfNum$asr_q105_p+ASRdfNum$asr_q108_p+ASRdfNum$asr_q119_p+ASRdfNum$asr_q121_p

ASRRulB=ASRdfNum$asr_q06_p+ASRdfNum$asr_q20_p+ASRdfNum$asr_q23_p+ASRdfNum$asr_q26_p+ASRdfNum$asr_q39_p+ASRdfNum$asr_q41_p+ASRdfNum$asr_q43_p+ASRdfNum$asr_q76_p+ASRdfNum$asr_q82_p+ASRdfNum$asr_q90_p+ASRdfNum$asr_q92_p+ASRdfNum$asr_q114_p+ASRdfNum$asr_q117_p+ASRdfNum$asr_q122_p

ASRAggr=ASRdfNum$asr_q03_p+ASRdfNum$asr_q05_p+ASRdfNum$asr_q16_p+ASRdfNum$asr_q28_p+ASRdfNum$asr_q37_p+ASRdfNum$asr_q55_p+ASRdfNum$asr_q57_p+ASRdfNum$asr_q68_p+ASRdfNum$asr_q81_p+ASRdfNum$asr_q86_p+ASRdfNum$asr_q87_p+ASRdfNum$asr_q95_p+ASRdfNum$asr_q97_p+ASRdfNum$asr_q113_p+ASRdfNum$asr_q116_p+ASRdfNum$asr_q118_p+ASRdfNum$asr_q06_p+ASRdfNum$asr_q20_p+ASRdfNum$asr_q23_p+ASRdfNum$asr_q26_p+ASRdfNum$asr_q39_p+ASRdfNum$asr_q41_p+ASRdfNum$asr_q43_p+ASRdfNum$asr_q76_p+ASRdfNum$asr_q82_p+ASRdfNum$asr_q90_p+ASRdfNum$asr_q92_p+ASRdfNum$asr_q114_p+ASRdfNum$asr_q117_p+ASRdfNum$asr_q122_p

# now internalizing and externalizing, to be equivalent with children
ASRInt=ASRWithdrawn+ASRSomatic

ASRExt=ASRAggr+ASRRulB
# and subtract reverse score items because they were included in sum above, and modeling "happiness" as symmetric to "symptoms" seems like a strong assumption
# reverse scored = face validity AND loading in expected direction
ASRtotal=ASRtotal-ASRdfNum$asr_q02_p
ASRtotal=ASRtotal-ASRdfNum$asr_q04_p
ASRtotal=ASRtotal-ASRdfNum$asr_q15_p
ASRtotal=ASRtotal-ASRdfNum$asr_q73_p
ASRtotal=ASRtotal-ASRdfNum$asr_q80_p
ASRtotal=ASRtotal-ASRdfNum$asr_q88_p
ASRtotal=ASRtotal-ASRdfNum$asr_q106_p
ASRtotal=ASRtotal-ASRdfNum$asr_q109_p
ASRtotal=ASRtotal-ASRdfNum$asr_q123_p

# merge in (first row is colnames)
asr$parentPcount=c(NA,ASRtotal)
asr$ASRAnxDepr=c(NA,ASRAnxDepr)
asr$ASRWithdrawn=c(NA,ASRWithdrawn)
asr$ASRSomatic=c(NA,ASRSomatic)
asr$ASRThought=c(NA,ASRThought)
asr$ASRAttn=c(NA,ASRAttn)
asr$ASRAggr=c(NA,ASRAggr)
asr$ASRRulB=c(NA,ASRRulB)
asr$ASRInt=c(NA,ASRInt)
asr$ASRExt=c(NA,ASRExt)
#

# fix asr age for merge
asr$interview_age=as.numeric(asr$interview_age)/12
# set src_subject_id to factor for merge
asr$src_subject_id<-as.factor(asr$src_subject_id)

# ensure none are missing
paste0(length(unique(masterdf$src_subject_id)))
# collapse to just variables of interest to prevent duplicate variables
asr=asr[,c('parentPcount','src_subject_id','eventname','interview_age','ASRAnxDepr','ASRWithdrawn','ASRSomatic','ASRThought','ASRAttn','ASRAggr','ASRRulB','ASRInt','ASRExt')]
# merge
masterdf=merge(masterdf,asr,by=c('src_subject_id','eventname','interview_age'))
# ensure none are missing
paste0(length(unique(masterdf$src_subject_id)))

```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
## Chunk 12 Handles participants TSV          ##
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

### LOAD in ParticipantsTSV for parent income and edu background
# ordained sample split
participantsTSV=read.delim('~/Downloads/participants.tsv',sep="\t")
participantsTSV$src_subject_id<-participantsTSV$participant_id
# reformat participant IDs so they match everything else
participantsTSV$src_subject_id<-gsub('sub-','',participantsTSV$src_subject_id)
participantsTSV$src_subject_id<-as.factor(gsub('NDARINV','NDAR_INV',participantsTSV$src_subject_id))
participantsTSV$eventname=participantsTSV$session_id
### issue where subjects are repeated. Rows are not identical either.
# query. get table of subject ids
b=table(as.factor(participantsTSV$participant_id))
# report subj ids used more than once and times used
bdf=data.frame(b[b>1])
SubjsRepeated=bdf$Var1
# well some rows with the same participant IDs have different sites, can't use that unless it makes sense
dimB4repRem=dim(participantsTSV)
# remove repeated subjs
participantsTSV=participantsTSV[!participantsTSV$participant_id %in% SubjsRepeated,]
dif=dimB4repRem[1]-dim(participantsTSV)[1]
print(paste0(dif/2,' Participants lost from ambiguously repeated pt ids in participants.tsv'))
# well some rows with the same participant IDs have different sites, can't use that unless it makes sense\
dimB4repRem=dim(participantsTSV)
# remove repeated subjs
participantsTSV=participantsTSV[!participantsTSV$participant_id %in% SubjsRepeated,]
# remove eventname column from participants tsv, not informative and causes problems down the road
participantsTSV = participantsTSV[,!(names(participantsTSV) %in% 'eventname')]
# convert sex to M/F in particpants tsv
participantsTSV$sex[participantsTSV$sex==1]="M"
participantsTSV$sex[participantsTSV$sex==2]="F"

# take out na incomes
participantsTSV=participantsTSV[participantsTSV$income!=777,]
participantsTSV=participantsTSV[participantsTSV$income!=999,]
# race
participantsTSV=participantsTSV[participantsTSV$race_ethnicity!=888,]
participantsTSV$race_ethnicity<-as.factor(participantsTSV$race_ethnicity)
# parental edu
participantsTSV=participantsTSV[participantsTSV$parental_education!=888,]
participantsTSV=participantsTSV[participantsTSV$parental_education!=777,]
participantsTSV$parental_education<-as.ordered(participantsTSV$parental_education)


#########################
#########################
#########################
#########################
### merge in for fam income and parent edu
masterdf=merge(masterdf,participantsTSV,by=c('src_subject_id','sex'))
# this dataframe is now your working data frame for all figure RMDs
saveRDS(masterdf,'~/gp_masterdf.rds')
####################
#########################
#########################
#########################

# new merge and count
participantsTSVSubjs=length(unique(masterdf$src_subject_id))
# add to included subjs DF
includedSubjects$pTSV=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$pTSV=1

print(paste0(newList6-participantsTSVSubjs,' participants lost after needing complete data in participantstsv'))
paste0(participantsTSVSubjs,' remain')
```

```{r}
# temp interactions with big 3 g and parental income 
# will re-download parent demographics to see if number of kids or INR explains dynamics better
Inc_P<-gam(cbcl_scr_syn_totprob_r~s(g)+s(income),data=masterdf,family=nb())
Inc_P_intrxn<-gam(cbcl_scr_syn_totprob_r~ti(g,income)+s(g)+s(income),data=masterdf,family=nb())
anova.gam(Inc_P,Inc_P_intrxn,test='Chisq')
# internalizing
Inc_Int<-gam(cbcl_scr_syn_internal_r~s(g)+s(income),data=masterdf,family=nb())
Inc_Int_intrxn<-gam(cbcl_scr_syn_internal_r~ti(g,income)+s(g)+s(income),data=masterdf,family=nb())
anova.gam(Inc_Int,Inc_Int_intrxn,test='Chisq')
Inc_Ext<-gam(cbcl_scr_syn_external_r~s(g)+s(income),data=masterdf,family=nb())
Inc_Ext_intrxn<-gam(cbcl_scr_syn_external_r~ti(g,income)+s(g)+s(income),data=masterdf,family=nb())
anova.gam(Inc_Ext,Inc_Ext_intrxn,test='Chisq')

g_Inc_P<-gam(g~s(cbcl_scr_syn_totprob_r)+s(income),data=masterdf)
g_Inc_P_intrxn<-gam(g~ti(cbcl_scr_syn_totprob_r,income)+s(cbcl_scr_syn_totprob_r)+s(income),data=masterdf)
anova.gam(g_Inc_P,g_Inc_P_intrxn,test='Chisq')
# internalizing
g_Inc_Int<-gam(g~s(cbcl_scr_syn_internal_r)+s(income),data=masterdf)
g_Inc_Int_intrxn<-gam(g~ti(cbcl_scr_syn_internal_r,income)+s(cbcl_scr_syn_internal_r)+s(income),data=masterdf)
anova.gam(g_Inc_Int,g_Inc_Int_intrxn,test='Chisq')
g_Inc_Ext<-gam(g~s(cbcl_scr_syn_external_r)+s(income),data=masterdf)
g_Inc_Ext_intrxn<-gam(g~ti(cbcl_scr_syn_external_r,income)+s(cbcl_scr_syn_external_r)+s(income),data=masterdf)
anova.gam(g_Inc_Ext,g_Inc_Ext_intrxn,test='Chisq')

# with NumKids

# with INR

```

```{r}

#### get more fine-grained demographics
fg_demo=read.delim('~/Downloads/Package_1206931/abcd_lpds01.txt',sep="\t")
# INR is Household Income : Poverty line for this # of people
# convert Household income
HouseholdIncome=as.factor(fg_demo$demo_comb_income_v2_l)
# to be replaced with numerican "median" income
fg_demo$HouseholdIncome=NULL
# to be replace with number of household members
fg_demo$NumPeeps=NULL
# to be replaced with number of people-specific poverty line
fg_demo$PL=NULL
# to be replaced with INR
fg_demo$INR=NULL

# 1 is less than 5k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==1]=median(c(0,5000))
# 2 is 5-12k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==2]=median(c(5000,11999))
# 3 is 12-16k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==3]=median(c(12000,15999))
# 4 is 16-25k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==4]=median(c(16000,24999))
# 5 25-35 k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==5]=median(c(25000,34999))
# 6 35-50 k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==6]=median(c(35000,49999))
# 7 50-75 k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==7]=median(c(50000,74999))
# 8 75-100 k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==8]=median(c(75000,99999))
# 9 100-200 k
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==9]=median(c(100000,199999))
# 10 > 200k: note 500k is top bound for median purposes
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==10]=median(c(200000,500000))
# 999 idk
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==999]=NA
# 777 refuse to answer
fg_demo$HouseholdIncome[fg_demo$demo_comb_income_v2_l==777]=NA
# convert number of people
fg_demo$NumPeeps=as.numeric(fg_demo$demo_roster_v2_l)
# Separate out income bins to match to their poverty line: https://aspe.hhs.gov/topics/poverty-economic-mobility/poverty-guidelines/prior-hhs-poverty-guidelines-federal-register-references/2017-poverty-guidelines
# 12,060 for 1 (note 1 should not be included in analyses, indicates child does not live there)
fg_demo$PL[fg_demo$NumPeeps==1]=12060
# 16,240 for 2
fg_demo$PL[fg_demo$NumPeeps==2]=16240
# 20,420 for 3
fg_demo$PL[fg_demo$NumPeeps==3]=20420
# 24,600 for 4
fg_demo$PL[fg_demo$NumPeeps==4]=24600
# 28,780 for 5
fg_demo$PL[fg_demo$NumPeeps==5]=28780
# 32,960 for 6
fg_demo$PL[fg_demo$NumPeeps==6]=32960
# 37,140 for 7
fg_demo$PL[fg_demo$NumPeeps==7]=37140
# 41,320 for 8
fg_demo$PL[fg_demo$NumPeeps==8]=41320
# 41,320 + 4,180 for 9
fg_demo$PL[fg_demo$NumPeeps==9]=45300
# 41,320 + 2*(4,180) for 10
fg_demo$PL[fg_demo$NumPeeps==10]=49480
# 41,320 + 3*(4,180) for 11
fg_demo$PL[fg_demo$NumPeeps==11]=53660
# 41,320 + 4*(4,180) for 12
fg_demo$PL[fg_demo$NumPeeps==12]=57840
# 41,320 + 5*(4,180) for 13
fg_demo$PL[fg_demo$NumPeeps==13]=62020
# 41,320 + 6*(4,180) for 14
fg_demo$PL[fg_demo$NumPeeps==14]=66200
# 41,320 + 7*(4,180) for 15
fg_demo$PL[fg_demo$NumPeeps==15]=70380
# 41,320 + 8*(4,180) for 16
fg_demo$PL[fg_demo$NumPeeps==16]=74560
# INR is Household Income : Poverty line for this # of people
fg_demo$INR=fg_demo$HouseholdIncome/fg_demo$PL
# new pov classification
fg_demo$Pov_v2=as.factor(fg_demo$HouseholdIncome<fg_demo$PL)

# fix age for merge
fg_demo$interview_age=as.numeric(fg_demo$interview_age)/12
# omit 3 year FUP
fg_demo=fg_demo[fg_demo$eventname!='3_year_follow_up_y_arm_1',]
fg_demo=fg_demo[fg_demo$eventname!='1_year_follow_up_y_arm_1',]
# retain only those with actual INR data
fg_demo=fg_demo[!is.na(fg_demo$INR),]
# merge back in
masterdf2=merge(masterdf,fg_demo,by=c('src_subject_id','sex','interview_age','eventname'))

# NEED cleaner version of fg_demo to not lose 80% of sample on merge

# new merge and count
parentDemo_TSVSubjs=length(unique(masterdf$src_subject_id))
# add to included subjs DF
includedSubjects$PD=0
includedSubjects[includedSubjects$subj %in% unique(masterdf$src_subject_id),]$PD=1

print(paste0(participantsTSVSubjs-parentDemo_TSVSubjs,' participants lost after needing complete data in Parent demographics'))
paste0(parentDemo_TSVSubjs,' remain')
```

```{r}
# load in kid self-report
youthReport=read.delim('~/Downloads/Package_1216656/abcd_ksad501.txt',sep="\t")
# filter out visits of non-interest
youthReport=youthReport[youthReport$eventname!='1_year_follow_up_y_arm_1',]

# get all column names with "Symptom - " as start, filter for those
SymptomColumns=colnames(youthReport)[grepl("Symptom - ",youthReport[1,])]
# out of those columns, get those ending in "Present", filter for those
SymptomPresentColumns=colnames(youthReport)[grepl("Present",youthReport[1,])]
# get intersection of two
SymptomPresentColumns=intersect(SymptomColumns,SymptomPresentColumns)

SymptomPresentColNamesChar=as.character(youthReport[1,SymptomPresentColumns])
#  [1] "Symptom - Depressed Mood, Present"                                                                     
#  [2] "Symptom - Irritability, Present"                                                                       
#  [3] "Symptom - Anhedonia, Present"                                                                          
#  [4] "Symptom - Elevated Mood, Present"                                                                      
#  [5] "Symptom - Explosive Irritability, Present"                                                             
#  [6] "Symptom - ExplosiveIrritability, PresentNext"                                                          
#  [7] "Symptom - Decreased Need for Sleep, Present"                                                           
#  [8] "Symptom - Hypersexuality, Present"                                                                     
#  [9] "Symptom - Hallucinations, Present"                                                                     
# [10] "Symptom - Persecutory Delusions, Past two weeks, Present"                                              
# [11] "Symptom - Panic Attacks, Present"                                                                      
# [12] "Symptom - Agoraphobic of at least 2 situations, Present"                                               
# [13] "Symptom - Distress upon separation from home/attachment figures, Present"                              
# [14] "Symptom - School Reluctance/Refusal, Present"                                                          
# [15] "Symptom - Fear of Social Situations Present"                                                           
# [16] "Symptom - Duration (at least 6 months) Present"                                                        
# [17] "Symptom - Failure to speak in social situations Present"                                               
# [18] "Symptom - Marked fear of phobic object Present"                                                        
# [19] "Symptom - Active avoidance of phobic object Present"                                                   
# [20] "Symptom - Impairment due to fear or avoidance of phobic object Present"                                
# [21] "Symptom - Distress due to fear or avoidance of phobic object Present"                                  
# [22] "Symptom - Duration of phobia at least 6 months Present"                                                
# [23] "Symptom - Excessive worries more days than not Present"                                                
# [24] "Symptom - Obsessions, Present"                                                                         
# [25] "Symptom - Compulsions, Present"                                                                        
# [26] "Symptom - Enuresis Present"                                                                            
# [27] "Symptom - Enuresis at least twice a week for 3 months Present"                                         
# [28] "Symptom - Enuresis causes significant distress Present"                                                
# [29] "Symptom - Impairment due to Enuresis Present"                                                          
# [30] "Symptom - Encopresis Present"                                                                          
# [31] "Symptom - Encopresis at least once a month for  3 months Present"                                      
# [32] "Symptom - Encopresis not due to medical illness Present"                                               
# [33] "Symptom - Fear of becoming obese Present"                                                              
# [34] "Symptom - Emaciation Present"                                                                          
# [35] "Symptom - Weight control vomiting Present"                                                             
# [36] "Symptom - Weight control other (laxatives exercise dieting pills) Present"                             
# [37] "Symptom - Binge Eating Present"                                                                        
# [38] "Symptom - Difficulty sustaining attention Present"                                                     
# [39] "Symptom - Difficulty sustaining attention since elementary school Present"                             
# [40] "Symptom - Easily distracted Present"                                                                   
# [41] "Symptom - Easily distracted since elementary school Present"                                           
# [42] "Symptom - Difficulty remaining seated Present"                                                         
# [43] "Symptom - Difficulty remaining seated since elementary school  Present"                                
# [44] "Symptom - Impulsivity Present"                                                                         
# [45] "Symptom - Often loses temper Present"                                                                  
# [46] "Symptom - Often argues with adults/authority Present"                                                  
# [47] "Symptom - Often disobeys rules/requests Present"                                                       
# [48] "Symptom - Often Lies, Present"                                                                         
# [49] "Symptom - Truancy, Present"                                                                            
# [50] "Symptom - Often initiates physical fights, Present"                                                    
# [51] "Symptom - Often bullies others, Present"                                                               
# [52] "Symptom - Stealing, Present"                                                                           
# [53] "Symptom - Motor Tics, Present"                                                                         
# [54] "Symptom - Phonic Tics, Present"                                                                        
# [55] "Symptom - Unusual body movements, Present"                                                             
# [56] "Symptom - Strict Routines, Present"                                                                    
# [57] "Symptom - Poor Eye Contact, Present"                                                                   
# [58] "Symptom - Often has three or more drinks a day, Present"                                               
# [59] "Symptom - Negative impact interpersonal problems, alcohol, Present"                                    
# [60] "Symptom - Drugs tried, Present"                                                                        
# [61] "Symptom - FrequencyDrugUse, Present"                                                                   
# [62] "Symptom - FrequencyDrugUseSpecial, Present"                                                            
# [63] "Symptom - Negative impact role obligations, miss work, drug use, Present"                              
# [64] "Symptom - Negative impact interpersonal problems, drug use, Present"                                   
# [65] "Symptom - History of traumatic event, Present"                                                         
# [66] "Symptom - Efforts to avoids thoughts of trauma, Present"                                               
# [67] "Symptom - Nightmares, Present"                                                                         
# [68] "Symptom - Distress at internal reminders of trauma, Present"                                           
# [69] "Symptom - Insomnia, Present"                                                                           
# [70] "Symptom - Self injurious behavior, Present"                                                            
# [71] "Symptom - Wishes/Better off dead, Present"                                                             
# [72] "Symptom - Suicidal Ideation, Present"                                                                  
# [73] "Symptom - Suicidal Attempt, Present"                                                                   
# [74] "Symptom - Homicidal Ideation, Present"                                                                 
# [75] "Symptom - Homicide Planning, Present"                                                                  
# [76] "Symptom - Hypersomnia, Present"                                                                        
# [77] "Symptom - Fatigue, Present"                                                                            
# [78] "Symptom - Concentration Disturbance, Present"                                                          
# [79] "Symptom - Indecision, Present"                                                                         
# [80] "Symptom - Decreased Appetite, Present"                                                                 
# [81] "Symptom - Weight Loss, Present"                                                                        
# [82] "Symptom - Increased Appetite, Present"                                                                 
# [83] "Symptom - Weight Gain, Present"                                                                        
# [84] "Symptom - Psychomotor Agitation in Depressive Disorder, Present"                                       
# [85] "Symptom - Psychomotor Retardation, Present"                                                            
# [86] "Symptom - Guilt, Present"                                                                              
# [87] "Symptom - Hopeless, Present"                                                                           
# [88] "Symptom - Decreased Self-Esteem, Present"                                                              
# [89] "Symptom - Impairment in functioning due to depression, Present"                                        
# [90] "Symptom - Presence of two or more depressive symptoms, Present"                                        
# [91] "Symptom - No two month symptom-free interval, Present"                                                 
# [92] "Symptom - Elevated / Euphoric Mood, Present"                                                           
# [93] "Symptom - Manic Irritability, Present"                                                                 
# [94] "Symptom - Grandiosity, Present"                                                                        
# [95] "Symptom - Pressured Speech, Present"                                                                   
# [96] "Symptom - Racing Thoughts, Present"                                                                    
# [97] "Symptom - Flight of Ideas, Present"                                                                    
# [98] "Symptom - Increased Goal Directed Activity, Present"                                                   
# [99] "Symptom - Increased Energy, Present"                                                                   
#[100] "Symptom - Psychomotor Agitation in Bipolar Disorder, Present"                                          
#[101] "Symptom - Distractibility, Present"                                                                    
#[102] "Symptom - Increased Distractibility, Present"                                                          
#[103] "Symptom - Excessive Involvement in high risk activities, Present"                                      
#[104] "Symptom - Impairment in functioning due to bipolar, Present"                                           
#[105] "Symptom - Hospitalized due to Bipolar Disorder, Present"                                               
#[106] "Symptom - Lasting at least one week, Present"                                                          
#[107] "Symptom - Lasting at least 4 days, Present"                                                            
#[108] "Symptom - Present at least 12 months"                                                                  
#[109] "Symptom - Auditory Hallucinations, Present"                                                            
#[110] "Symptom - Other Hallucinations, Present"                                                               
#[111] "Symptom - Location of voices/noises outside of one's head, Present"                                    
#[112] "Symptom - OtherHallucinationsALTW, Present"                                                            
#[113] "Symptom - OtherHallucinationsAP, Present"                                                              
#[114] "Symptom - Hallucinations occur frequently, Present"                                                    
#[115] "Symptom - Hallucinations do not only occur when falling asleep, Present"                               
#[116] "Symptom - Hallucinations associated with possible affective Illness, Present"                          
#[117] "Symptom - Hallucinations associated with drug use, Present"                                            
#[118] "Symptom - Impairment in functioning due to hallucinations, Present"                                    
#[119] "Symptom - Impairment in functioning due to delusions, Present"                                         
#[120] "Symptom - Other Delusions past two weeks, Present"                                                     
#[121] "Symptom - Tenacity of belief that delusion is true, Present"                                           
#[122] "Symptom - Delusions associated with possible affective Illness, Present"                               
#[123] "Symptom - Delusions associated with drug use, Present"                                                 
#[124] "Symptom - Impairment associated with delusions, Present"                                               
#[125] "Symptom - Associated Psychotic Symptoms, Present"                                                      
#[126] "Symptom - Panic Symptoms, Present"                                                                     
#[127] "Symptom - Persistent worry about additional attacks or their consequences, Present"                    
#[128] "Symptom - Maladaptive change in behavior due to attacks, Present"                                      
#[129] "Symptom - Duration of worry or maladaptive behavior at least 1 month, Present"                         
#[130] "Symptom - Attacks not attributable to substance use, Present"                                          
#[131] "Symptom - Excessive avoidance of agoraphobic situations, Present"                                      
#[132] "Symptom - Reason for agoraphobic avoidance, Present"                                                   
#[133] "Symptom - Impairment in functioning due to Agoraphobia, Present"                                       
#[134] "Symptom - Clinically significant distress due to Agoraphobia, Present"                                 
#[135] "Symptom - Fears calamitous event that will cause separation, Present"                                  
#[136] "Symptom - Worry about harm befalling attachment figure, Present"                                       
#[137] "Symptom - Fear of being alone without attachment figure, Present"                                      
#[138] "Symptom - Refusal to sleep without attachment figure near, Present"                                    
#[139] "Symptom - Nightmares about separation themes, Present"                                                 
#[140] "Symptom - Physical symptoms when separated from attachment figure, Present"                            
#[141] "Symptom - Impairment in functioning due to separation anxiety, Present"                                
#[142] "Symptom - Clinically significant distress due to separation anxiety, Present"                          
#[143] "Symptom - Separation anxiety duration is at least 4 weeks, Present"                                    
#[144] "Symptom - Social situations invariably provoke anxiety, Present"                                       
#[145] "Symptom - Social situations avoided or endured with distress, Present"                                 
#[146] "Symptom - Social fear is excessive given threat or sociocultural context, Present"                     
#[147] "Symptom - Impairment in functioning due to social anxiety, Present"                                    
#[148] "Symptom - Clinically significant distress due to Social Anxiety, Present"                              
#[149] "Symptom - Reasons for mutism not due to inability to speak language, Present"                          
#[150] "Symptom - Impairment in functioning due to selective mutism, Present"                                  
#[151] "Symptom - Duration at least month for selective mutism, Present"                                       
#[152] "Symptom - Excessive worries across breadth of domains, Present"                                        
#[153] "Symptom - Worry associated with defined symptom(s), Present"                                           
#[154] "Symptom - Difficulty controlling worries, Present"                                                     
#[155] "Symptom - Impairment in functioning due to worries, Present"                                           
#[156] "Symptom - Clinically significant distress due to worries, Present"                                     
#[157] "Symptom - Obsessive thoughts experienced as Intrusive/unwanted, Present"                               
#[158] "Symptom - Attempts to suppress or neutralize thoughts, Present"                                        
#[159] "Symptom - Obsessions time consuming, Present"                                                          
#[160] "Symptom - Impairment in functioning due to obsessions, Present"                                        
#[161] "Symptom - Clinically significant distress due to obsessions, Present"                                  
#[162] "Symptom - Compulsions time consuming, Present"                                                         
#[163] "Symptom - Purpose of compulsions to prevent/reduce anxiety or prevent dreaded event, Present"          
#[164] "Symptom - Impairment in functioning due to compulsions, Present"                                       
#[165] "Symptom - Clinically significant distress due to compulsions, Present"                                 
#[166] "Symptom - Intrusive distressing thoughts about the trauma , Present"                                   
#[167] "Symptom - Dissociative reactions (flashbacks), Present"                                                
#[168] "Symptom - Distress at reminders, external cues, Present"                                               
#[169] "Symptom - Physiological reactivity to reminders of trauma, Present"                                    
#[170] "Symptom - Inability to recall aspects of trauma, Present"                                              
#[171] "Symptom - Persistent negative beliefs or expectations, Present"                                        
#[172] "Symptom - Distorted cognitions about the causes of the trauma, Present"                                
#[173] "Symptom - Distorted cognitions about the consequences of the trauma, Present"                          
#[174] "Symptom - Persistent negative emotional states, Present"                                               
#[175] "Symptom - Feelings of Feelings of detachment, Present"                                                 
#[176] "Symptom - Inability to experience positive emotions, Present"                                          
#[177] "Symptom - Irritable or aggressive behavior, Present"                                                   
#[178] "Symptom - Reckless or self-destructive behavior, Present"                                              
#[179] "Symptom - Hypervigilance, Present"                                                                     
#[180] "Symptom - Exaggerated startle response, Present"                                                       
#[181] "Symptom - Concentration problems, Present"                                                             
#[182] "Symptom - Sleep disturbance, Present"                                                                  
#[183] "Symptom - Efforts to avoid external reminders of trauma, Present"                                      
#[184] "Symptom - Impairment in functioning due to PTSD, Present"                                              
#[185] "Symptom - Clinically significant distress due to PTSD, Present"                                        
#[186] "Symptom - Anhedonia related to PTSD, Present"                                                          
#[187] "Symptom - Duration at least one month, Present"                                                        
#[188] "Symptom - Often makes careless mistakes, Present"                                                      
#[189] "Symptom - Often doesn't seem to listen when spoken to, Present"                                        
#[190] "Symptom - Difficulty following Instructions, Present"                                                  
#[191] "Symptom - Difficulty organizing tasks, Present"                                                        
#[192] "Symptom - Avoids tasks requiring attention, Present"                                                   
#[193] "Symptom - Often loses things, Present"                                                                 
#[194] "Symptom - Forgetful in daily activities, Present"                                                      
#[195] "Symptom - Fidgets, Present"                                                                            
#[196] "Symptom - Runs or climbs excessively, Present"                                                         
#[197] "Symptom - Acts like driven by a motor, Present"                                                        
#[198] "Symptom - Difficulty playing quietly, Present"                                                         
#[199] "Symptom - Blurts out answers, Present"                                                                 
#[200] "Symptom - Difficulty waiting turn, Present"                                                            
#[201] "Symptom - Often Interrupts or intrudes on others, Present"                                             
#[202] "Symptom - Often talks excessively, Present"                                                            
#[203] "Symptom - Symptoms interfere with social, academic or occupational functioning, Present"               
#[204] "Symptom - Several symptoms present prior to age 12 years, Present"                                     
#[205] "Symptom - Often touchy or easily annoyed, Present"                                                     
#[206] "Symptom - Often angry or resentful, Present"                                                           
#[207] "Symptom - Spiteful or vindictive, Present"                                                             
#[208] "Symptom - Often deliberatively annoys people, Present"                                                 
#[209] "Symptom - Often blames others for own mistakes, Present"                                               
#[210] "Symptom - Causes problems in functioning or distress in self or others, Present"                       
#[211] "Symptom - Duration of at least 6 months, Present"                                                      
#[212] "Symptom - Vandalism, Present"                                                                          
#[213] "Symptom - Breaking and entering, Present"                                                              
#[214] "Symptom - Stealing while confronting victim, Present"                                                  
#[215] "Symptom - Fire setting, Present"                                                                       
#[216] "Symptom - Stays out late at night despite parental prohibition, Present"                               
#[217] "Symptom - Ran away overnight, Present"                                                                 
#[218] "Symptom - Use of a weapon that can cause serious harm, Present"                                        
#[219] "Symptom - Has been physically cruel to people, Present"                                                
#[220] "Symptom - Forced someone into sexual activity, Present"                                                
#[221] "Symptom - Has been physically cruel to animals, Present"                                               
#[222] "Symptom - Self-worth tied to weight, Present"                                                          
#[223] "Symptom - Inappropriate compensatory behaviors to prevent weight gain, Present"                        
#[224] "Symptom - Compensatory behaviors occur at least 1x/week for 3 months, Present"                         
#[225] "Symptom - Binge eating occur at least 1x/week for 3 months, Present"                                   
#[226] "Symptom - CharacteristicsofBinge Eating, Present"                                                      
#[227] "Symptom - Distress associated with binge eating, Present"                                              
#[228] "Symptom - Drinks More than Planned, Present"                                                           
#[229] "Symptom - Failure to fulfill major role responsibilities due to alcohol use, Present"                  
#[230] "Symptom - Recurrent alcohol use in situations that are physically hazardous, Present"                  
#[231] "Symptom - Use of alcohol/intoxicated while driving, Present"                                           
#[232] "Symptom - Recurrent physical problems due to alcohol, Present"                                         
#[233] "Symptom - Recurrent psychological problems due to alcohol, Present"                                    
#[234] "Symptom - Craving, or a strong desire to use alcohol, Present"                                         
#[235] "Symptom - Important activities given up or reduced due to alcohol, Present"                            
#[236] "Symptom - Persistent desire to reduce alcohol use, Present"                                            
#[237] "Symptom - Unsuccessful efforts to reduce alcohol use, Present"                                         
#[238] "Symptom - Alcohol Withdrawal, Present"                                                                 
#[239] "Symptom - Alcohol Tolerance, Present"                                                                  
#[240] "Symptom - Great deal of time obtaining, using or recovering from alcohol, Present"                     
#[241] "Symptom - Alcohol Abstinence, Present"                                                                 
#[242] "Symptom - Often used more of substance than planned, Present"                                          
#[243] "Symptom - Failure to fulfill major role responsibilities due to substance use, Present"                
#[244] "Symptom - Substance use in physically dangerous situations, Present"                                   
#[245] "Symptom - Use of substance/intoxicated while driving, Present"                                         
#[246] "Symptom - Physical problems due to substance use, Present"                                             
#[247] "Symptom - Psychological problems due to substance use, Present"                                        
#[248] "Symptom - Craving, or strong desire to use substance, Present"                                         
#[249] "Symptom - Important activities given up or reduced due to substance use, Present"                      
#[250] "Symptom - Persistent desire to reduce substance use, Present"                                          
#[251] "Symptom - Unsuccessful efforts to reduce substance use, Present"                                       
#[252] "Symptom - Substance Withdrawal, Present"                                                               
#[253] "Symptom - Substance Tolerance, Present"                                                                
#[254] "Symptom - Great deal of time obtaining, using or recovering from substance use, Present"               
#[255] "Symptom - Substance Use Abstinence, Present"                                                           
#[256] "Symptom - Negative impact role obligations, miss work, drug use (Cannabis), Present"                   
#[257] "Symptom - Failure to fulfill major role responsibilities due to substance use (Cannabis), Present"     
#[258] "Symptom - Negative impact interpersonal problems, drug use (Cannabis), Present"                        
#[259] "Symptom - Often used more of substance than planned (Cannabis), Present"                               
#[260] "Symptom - Use of substance/intoxicated while driving (Cannabis), Present"                              
#[261] "Symptom - Substance use in physically dangerous situations (Cannabis), Present"                        
#[262] "Symptom - Physical problems due to substance use (Cannabis), Present"                                  
#[263] "Symptom - Psychological problems due to substance use(Cannabis), Present"                              
#[264] "Symptom - Craving, or strong desire to use substance (Cannabis), Present"                              
#[265] "Symptom - Important activities given up or reduced due to substance use (Cannabis), Present"           
#[266] "Symptom - Persistent desire to reduce substance use (Cannabis), Present"                               
#[267] "Symptom - Unsuccessful efforts to reduce substance use (Cannabis), Present"                            
#[268] "Symptom - Substance Withdrawal (Cannabis), Present"                                                    
#[269] "Symptom - Substance Tolerance (Cannabis), Present"                                                     
#[270] "Symptom - Great deal of time obtaining, using or recovering from substance use (Cannabis), Present"    
#[271] "Symptom - Negative impact role obligations, miss work, drug use (Stimulants), Present"                 
#[272] "Symptom - Failure to fulfill major role responsibilities due to substance use (Stimulants), Present"   
#[273] "Symptom - Negative impact interpersonal problems, drug use (Stimulants), Present"                      
#[274] "Symptom - Often used more of substance than planned (Stimulants), Present"                             
#[275] "Symptom - Use of substance/intoxicated while driving (Stimulants), Present"                            
#[276] "Symptom - Substance use in physically dangerous situations (Stimulants), Present"                      
#[277] "Symptom - Physical problems due to substance use (Stimulants), Present"                                
#[278] "Symptom - Psychological problems due to substance use (Stimulants), Present"                           
#[279] "Symptom - Craving, or strong desire to use substance (Stimulants), Present"                            
#[280] "Symptom - Important activities given up or reduced due to substance use (Stimulants), Present"         
#[281] "Symptom - Persistent desire to reduce substance use (Stimulants), Present"                             
#[282] "Symptom - Unsuccessful efforts to reduce substance use (Stimulants), Present"                          
#[283] "Symptom - Substance Withdrawal (Stimulants), Present"                                                  
#[284] "Symptom - Substance Tolerance (Stimulants), Present"                                                   
#[285] "Symptom - Great deal of time obtaining, using or recovering from substance use (Stimulants), Present"  
#[286] "Symptom - Negative impact role obligations, miss work, drug use (Sedatives), Present"                  
#[287] "Symptom - Failure to fulfill major role responsibilities due to substance use (Sedatives), Present"    
#[288] "Symptom - Negative impact interpersonal problems, drug use (Sedatives), Present"                       
#[289] "Symptom - Often used more of substance than planned (Sedatives), Present"                              
#[290] "Symptom - Use of substance/intoxicated while driving (Sedatives), Present"                             
#[291] "Symptom - Substance use in physically dangerous situations (Sedatives), Present"                       
#[292] "Symptom - Physical problems due to substance use (Sedatives), Present"                                 
#[293] "Symptom - Psychological problems due to substance use(Sedatives), Present"                             
#[294] "Symptom - Craving, or strong desire to use substance (Sedatives), Present"                             
#[295] "Symptom - Important activities given up or reduced due to substance use (Sedatives), Present"          
#[296] "Symptom - Persistent desire to reduce substance use (Sedatives), Present"                              
#[297] "Symptom - Unsuccessful efforts to reduce substance use (Sedatives), Present"                           
#[298] "Symptom - Substance Withdrawal (Sedatives), Present"                                                   
#[299] "Symptom - Substance Tolerance (Sedatives), Present"                                                    
#[300] "Symptom - Great deal of time obtaining, using or recovering from substance use (Sedatives), Present"   
#[301] "Symptom - Negative impact role obligations, miss work, drug use (Cocaine), Present"                    
#[302] "Symptom - Failure to fulfill major role responsibilities due to substance use (Cocaine), Present"      
#[303] "Symptom - Negative impact interpersonal problems, drug use (Cocaine), Present"                         
#[304] "Symptom - Often used more of substance than planned (Cocaine), Present"                                
#[305] "Symptom - Use of substance/intoxicated while driving (Cocaine), Present"                               
#[306] "Symptom - Substance use in physically dangerous situations (Cocaine), Present"                         
#[307] "Symptom - Physical problems due to substance use (Cocaine), Present"                                   
#[308] "Symptom - Psychological problems due to substance use(Cocaine), Present"                               
#[309] "Symptom - Craving, or strong desire to use substance (Cocaine), Present"                               
#[310] "Symptom - Important activities given up or reduced due to substance use (Cocaine), Present"            
#[311] "Symptom - Persistent desire to reduce substance use (Cocaine), Present"                                
#[312] "Symptom - Unsuccessful efforts to reduce substance use (Cocaine), Present"                             
#[313] "Symptom - Substance Withdrawal (Cocaine), Present"                                                     
#[314] "Symptom - Substance Tolerance (Cocaine), Present"                                                      
#[315] "Symptom - Great deal of time obtaining, using or recovering from substance use (Cocaine), Present"     
#[316] "Symptom - Negative impact role obligations, miss work, drug use (Opioid), Present"                     
#[317] "Symptom - Failure to fulfill major role responsibilities due to substance use (Opioid), Present"       
#[318] "Symptom - Negative impact interpersonal problems, drug use (Opioid), Present"                          
#[319] "Symptom - Often used more of substance than planned (Opioid), Present"                                 
#[320] "Symptom - Use of substance/intoxicated while driving (Opioid), Present"                                
#[321] "Symptom - Substance use in physically dangerous situations (Opioid), Present"                          
#[322] "Symptom - Physical problems due to substance use (Opioid), Present"                                    
#[323] "Symptom - Psychological problems due to substance use(Opioid), Present"                                
#[324] "Symptom - Craving, or strong desire to use substance (Opioid), Present"                                
#[325] "Symptom - Important activities given up or reduced due to substance use (Opioid), Present"             
#[326] "Symptom - Persistent desire to reduce substance use (Opioid), Present"                                 
#[327] "Symptom - Unsuccessful efforts to reduce substance use (Opioid), Present"                              
#[328] "Symptom - Substance Withdrawal (Opioid), Present"                                                      
#[329] "Symptom - Substance Tolerance (Opioid), Present"                                                       
#[330] "Symptom - Great deal of time obtaining, using or recovering from substance use (Opioid), Present"      
#[331] "Symptom - Negative impact role obligations, miss work, drug use (Hallucinogen), Present"               
#[332] "Symptom - Failure to fulfill major role responsibilities due to substance use (Hallucinogen), Present" 
#[333] "Symptom - Negative impact interpersonal problems, drug use (Hallucinogen), Present"                    
#[334] "Symptom - Often used more of substance than planned (Hallucinogen), Present"                           
#[335] "Symptom - Use of substance/intoxicated while driving (Hallucinogen), Present"                          
#[336] "Symptom - Substance use in physically dangerous situations (Hallucinogen), Present"                    
#[337] "Symptom - Physical problems due to substance use (Hallucinogen), Present"                              
#[338] "Symptom - Psychological problems due to substance use(Hallucinogen), Present"                          
#[339] "Symptom - Craving, or strong desire to use substance (Hallucinogen), Present"                          
#[340] "Symptom - Important activities given up or reduced due to substance use (Hallucinogen), Present"       
#[341] "Symptom - Persistent desire to reduce substance use (Hallucinogen), Present"                           
#[342] "Symptom - Unsuccessful efforts to reduce substance use (Hallucinogen), Present"                        
#[343] "Symptom - Substance Withdrawal (Hallucinogen), Present"                                                
#[344] "Symptom - Substance Tolerance (Hallucinogen), Present"                                                 
#[345] "Symptom - Great deal of time obtaining, using or recovering from substance use (Hallucinogen), Present"
#[346] "Symptom - Negative impact role obligations, miss work, drug use (Tobacco), Present"                    
#[347] "Symptom - Failure to fulfill major role responsibilities due to substance use (Tobacco), Present"      
#[348] "Symptom - Negative impact interpersonal problems, drug use (Tobacco), Present"                         
#[349] "Symptom - Often used more of substance than planned (Tobacco), Present"                                
#[350] "Symptom - Use of substance/intoxicated while driving (Tobacco), Present"                               
#[351] "Symptom - Substance use in physically dangerous situations (Tobacco), Present"                         
#[352] "Symptom - Physical problems due to substance use (Tobacco), Present"                                   
#[353] "Symptom - Psychological problems due to substance use(Tobacco), Present"                               
#[354] "Symptom - Craving, or strong desire to use substance (Tobacco), Present"                               
#[355] "Symptom - Important activities given up or reduced due to substance use (Tobacco), Present"            
#[356] "Symptom - Persistent desire to reduce substance use (Tobacco), Present"                                
#[357] "Symptom - Unsuccessful efforts to reduce substance use (Tobacco), Present"                             
#[358] "Symptom - Substance Withdrawal (Tobacco), Present"                                                     
#[359] "Symptom - Substance Tolerance (Tobacco), Present"                                                      
#[360] "Symptom - Great deal of time obtaining, using or recovering from substance use (Tobacco), Present"     
#[361] "Symptom - Negative impact role obligations, miss work, drug use (Solvent), Present"                    
#[362] "Symptom - Failure to fulfill major role responsibilities due to substance use (Solvent), Present"      
#[363] "Symptom - Negative impact interpersonal problems, drug use (Solvent), Present"                         
#[364] "Symptom - Often used more of substance than planned (Solvent), Present"                                
#[365] "Symptom - Use of substance/intoxicated while driving (Solvent), Present"                               
#[366] "Symptom - Substance use in physically dangerous situations (Solvent), Present"                         
#[367] "Symptom - Physical problems due to substance use (Solvent), Present"                                   
#[368] "Symptom - Psychological problems due to substance use (Solvent), Present"                              
#[369] "Symptom - Craving, or strong desire to use substance (Solvent), Present"                               
#[370] "Symptom - Important activities given up or reduced due to substance use (Solvent), Present"            
#[371] "Symptom - Persistent desire to reduce substance use (Solvent), Present"                                
#[372] "Symptom - Unsuccessful efforts to reduce substance use (Solvent), Present"                             
#[373] "Symptom - Substance Withdrawal (Solvent), Present"                                                     
#[374] "Symptom - Substance Tolerance (Solvent), Present"                                                      
#[375] "Symptom - Great deal of time obtaining, using or recovering from substance use (Solvent), Present"     
#[376] "Symptom - Negative impact role obligations, miss work, drug use (Other Drugs), Present"                
#[377] "Symptom - Failure to fulfill major role responsibilities due to substance use (Other Drugs), Present"  
#[378] "Symptom - Negative impact interpersonal problems, drug use (Other Drugs), Present"                     
#[379] "Symptom - Often used more of substance than planned (Other Drugs), Present"                            
#[380] "Symptom - Use of substance/intoxicated while driving (Other Drugs), Present"                           
#[381] "Symptom - Substance use in physically dangerous situations (Other Drugs), Present"                     
#[382] "Symptom - Physical problems due to substance use (Other Drugs), Present"                               
#[383] "Symptom - Psychological problems due to substance use (Other Drugs), Present"                          
#[384] "Symptom - Craving, or strong desire to use substance (Other Drugs), Present"                           
#[385] "Symptom - Important activities given up or reduced due to substance use (Other Drugs), Present"        
#[386] "Symptom - Persistent desire to reduce substance use (Other Drugs), Present"                            
#[387] "Symptom - Unsuccessful efforts to reduce substance use (Other Drugs), Present"                         
#[388] "Symptom - Substance Withdrawal (Other Drugs), Present"                                                 
#[389] "Symptom - Substance Tolerance (Other Drugs), Present"                                                  
#[390] "Symptom - Great deal of time obtaining, using or recovering from substance use (Other Drugs), Present" 
#[391] "Symptom - Self-injury, intent to die, Present"                                                         
#[392] "Symptom - Self-Injury, thought could die from behavior, Present"                                       
#[393] "Symptom - Suicidal ideation thought of method, Present"                                                
#[394] "Symptom - Suicidal ideation, intent to act, Present"                                                   
#[395] "Symptom - Suicidal ideation, specific plan, Present"                                                   
#[396] "Symptom - Suicidal behavior, made preparations, Present"                                               
#[397] "Symptom - Aborted or interrupted suicide attempts, Present"                                            
#[398] "Symptom - Method of actual suicide attempt, Present"                                                   
#[399] "Symptom - Suicide attempt, thought could die, Present"                                                 
#[400] "Symptom - Duration of past phobia at least 6 months, Present"                                          
#[401] "Symptom - Worrying has lasted at least 6 months, Present"                                              

int<-c(1,3,11,12,13,15,16,18,19,20,21,22,23,24,33,34,35,36,37,66,67,68,69,71,72,76,77,80,81,82,83,84,86,87,88,80,90,91,92,96,97,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,169,171,172,173,174,176,180,184,185,186,187,222,223,224,225,226,227,391,392,393,394,395,396,397,398,399,400,401)

ext<-c(2,5,6,8,14,17,25,26,27,28,29,30,31,32,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,70,73,74,75,78,85,93,94,95,101,102,103,149,150,151,177,178,181,188,189,190,191,191,192,193,194,195,196,197,198,199,200,201,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,228:390)

other<-c(4,7,9,10,65,79,98,99,100,104,105,106,107,108,109,110,111,112,113,114,115,115,117,118,119,120,121,122,123,124,125,167,168,170,179,182,183)
                             
# replace "" with "0", "555" with "0", "888" with 0 in these columns
youthReport[,SymptomPresentColumns][youthReport[,SymptomPresentColumns]==""]=0
youthReport[,SymptomPresentColumns][youthReport[,SymptomPresentColumns]=="555"]=0
youthReport[,SymptomPresentColumns][youthReport[,SymptomPresentColumns]=="888"]=0
# convert these columns to numeric (0 and "0", 1 at "1")
youthReport[,SymptomPresentColumns]=apply(youthReport[,SymptomPresentColumns],2,as.numeric)
# get a sum 'p' factor across all metrics
youthReport$ksads_scr_syn_totprob_r=rowSums(youthReport[,SymptomPresentColumns])
# internalizing
youthReport$ksads_scr_syn_internal_r=rowSums(youthReport[,SymptomPresentColumns[int]])
# externalizing
youthReport$ksads_scr_syn_external_r=rowSums(youthReport[,SymptomPresentColumns[ext]])
# fix age and merge
youthReport$interview_age=as.numeric(youthReport$interview_age)/12
# remove folks with missing time stamp
youthReport=youthReport[youthReport$ksads_duration_t!='',]
masterdf2=merge(masterdf,youthReport,by=c('src_subject_id','sex','interview_age','eventname'))

# get difference measure: 
# z-score of child on parent report cbcl_scr_syn_totprob_r
masterdf2$cbcl_scr_syn_totprob_z=(masterdf2$cbcl_scr_syn_totprob_r-mean(masterdf2$cbcl_scr_syn_totprob_r))/sd(masterdf2$cbcl_scr_syn_totprob_r)
# z score of self-report ksads_scr_syn_totprob_r
masterdf2$ksads_scr_syn_totprob_z=(masterdf2$ksads_scr_syn_totprob_r-mean(masterdf2$ksads_scr_syn_totprob_r))/sd(masterdf2$ksads_scr_syn_totprob_r)
# get difference
masterdf2$cbcl_ksads_diff=masterdf2$cbcl_scr_syn_totprob_z-masterdf2$ksads_scr_syn_totprob_z


# note interactions between parent report and child report symptoms for g
```

```{r}
# pull clinical cutoff from master df: t scores > 65 = borderline clinical, 69 = clinical
# https://onlinelibrary.wiley.com/doi/epdf/10.1002/mrdd.20071
# https://aseba.org/wp-content/uploads/2019/02/cbclprofile.pdf
masterdfP_bc<-masterdf[masterdf$cbcl_scr_syn_totprob_t==65,]
masterdfP_c<-masterdf[masterdf$cbcl_scr_syn_totprob_t==69,]
# borderline clinical and clinical cutoffs
Pbc=mean(masterdfP_bc$cbcl_scr_syn_totprob_r)
Pc=mean(masterdfP_c$cbcl_scr_syn_totprob_r)
masterdfI_bc<-masterdf[masterdf$cbcl_scr_syn_internal_t==65,]
masterdfI_c<-masterdf[masterdf$cbcl_scr_syn_internal_t==69,]
masterdfE_bc<-masterdf[masterdf$cbcl_scr_syn_external_t==65,]
masterdfE_c<-masterdf[masterdf$cbcl_scr_syn_external_t==69,]
Ibc=mean(masterdfP_bc$cbcl_scr_syn_internal_r)
Ic=mean(masterdfP_c$cbcl_scr_syn_internal_r)
Ebc=mean(masterdfE_bc$cbcl_scr_syn_external_r)
Ec=mean(masterdfE_c$cbcl_scr_syn_external_r)
# Save out Clinical-only DFs
CO_df=masterdf[masterdf$cbcl_scr_syn_totprob_r>Pc,]
saveRDS(CO_df,'~/gp_COp_masterdf.rds')
CO_df=masterdf[masterdf$cbcl_scr_syn_internal_r>Ic,]
saveRDS(CO_df,'~/gp_COi_masterdf.rds')
CO_df=masterdf[masterdf$cbcl_scr_syn_external_r>Ec,]
saveRDS(CO_df,'~/gp_COe_masterdf.rds')
# save out Subclinical-only DFs
SCO_df=masterdf[masterdf$cbcl_scr_syn_totprob_r<Pbc,]
saveRDS(SCO_df,'~/gp_SCOp_masterdf.rds')
SCO_df=masterdf[masterdf$cbcl_scr_syn_internal_r<Pbc,]
saveRDS(SCO_df,'~/gp_SCOi_masterdf.rds')
SCO_df=masterdf[masterdf$cbcl_scr_syn_external_r<Pbc,]
saveRDS(SCO_df,'~/gp_SCOe_masterdf.rds')

# randomize splits
SubjsFull=unique(masterdf$src_subject_id)
set.seed(1)
SH1_subjs=sample(SubjsFull,length(SubjsFull)/2,replace = F)
SH2_subjs=setdiff(SubjsFull,SH1_subjs)
# Save out split-half 1 df
SH1=masterdf[masterdf$src_subject_id %in% SH1_subjs,]
saveRDS(SCO_df,'~/gp_SH1_masterdf.rds')
# save out split-half 2 df
SH2=masterdf[masterdf$src_subject_id %in% SH2_subjs,]
saveRDS(SH2,'~/gp_SH2_masterdf.rds')

```

```{r, echo=FALSE, fig.dim = c(20, 6)}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
#### Chunk 13 plots data missingness       #####
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# melt the plot df to get in proper format
plotdf=melt(includedSubjects)
plotdf$value<-as.factor(plotdf$value)
plotdf$subj<-as.factor(plotdf$subj)
# merge in raceEth of each subj
raceEth=participantsTSV$race_ethnicity
subjectsInPtsv=participantsTSV$src_subject_id
infoDf=data.frame(raceEth,subjectsInPtsv)
colnames(infoDf)<-c('RaceEthn','subj')
plotdf2=merge(plotdf,infoDf,by='subj')

# remove participants tsv stratum, as the depicted stratum are predicated on participants tsv data being present
plotdf2=plotdf2[plotdf2$variable!='pTSV',]
# overwrite race with "empty" if missing after each checkpoint
plotdf2$RaceEthn<-factor(plotdf2$RaceEthn,levels=c(1,2,3,4,5,6),labels=c("White","Black","Hispanic","Asian","Other","Missing"))
plotdf2$RaceEthn[plotdf2$value==0]="Missing"
alph_order <- c("Asian", "Black", "Hispanic", "Missing", "Other", "White")

# preset some color
my_colors <- c("red", "orange", "blue", "gray", "green","yellow")

# preset x-axis names
x_labs=c("CBCL", "CBCL (both timepoints)","Grades (both)","ASR (both)","ACS","Cognitive data (both)","One sibling per family")

#
ggplot(plotdf2, aes(x = variable, stratum = RaceEthn, alluvium = subj)) +
  geom_stratum(aes(fill = factor(RaceEthn, levels = alph_order))) +
  geom_flow(aes(fill = factor(RaceEthn, levels = alph_order))) +
  scale_fill_manual(values = my_colors, breaks = alph_order) +
  theme_bw(base_size = 30) + 
  labs(y = "Children", fill = "Race/Ethnicity", title = "Alluvial Consort Chart") +
  scale_x_discrete(labels = x_labs) +
  theme(axis.title.x = element_blank())


```

```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############
#### Chunk 14 plots  missingness as pie charts #
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆##############

# can overlay two pie charts: starting raceEth Comp and Ending. Tuck into area that is pink now
startingdf=plotdf2[plotdf2$variable=='cbclInclude',]
startingdf=startingdf[startingdf$value==1,]
endingdf=plotdf2[plotdf2$variable=='pTSV',]
endingdf=endingdf[endingdf$value==1,]
# now tabulate them to get in proper plotting format
startingdfTab=tabulate(startingdf$RaceEthn)
endingdfTab=tabulate(endingdf$RaceEthn)
# starting df: adding 0 for placeholder for missing category (consistent coloration)
startingdf=data.frame(c(startingdfTab,0),factor(c("White","Black","Hispanic","Asian","Other","Missing"),levels=c("White","Black","Hispanic","Asian","Other","Missing")))
colnames(startingdf)<-c('value','RaceEthnicity')

# now make color assignment equivalent

ggplot(startingdf, aes(x="", y=value, fill = factor(RaceEthnicity, levels = alph_order))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+ggtitle('Before Exclusions')+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank(),panel.background = element_blank(),
        plot.title = element_text(size = 30),
        legend.text = element_text(size=30),legend.title = element_blank())+scale_fill_manual(values = my_colors)

# plot df is both with race labels
endingdf=data.frame(c(endingdfTab,0),factor(c("White","Black","Hispanic","Asian","Other","Missing"),levels=c("White","Black","Hispanic","Asian","Other","Missing")))
colnames(endingdf)<-c('value','RaceEthnicity')
ggplot(endingdf, aes(x="", y=value, fill = factor(RaceEthnicity, levels = alph_order))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+ggtitle('After Exclusions')+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank(),panel.background = element_blank(),
        plot.title = element_text(size = 30),
        legend.text = element_text(size=30),legend.title = element_blank())+scale_fill_manual(values = my_colors)
```


```{r}
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆################################
#### Chunk 15 prepares data for analysis of temporal precedence ##
###########∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆################################
variablesOfInterest=c('cbcl_scr_syn_totprob_r','cbcl_scr_syn_external_r','cbcl_scr_syn_internal_r','g','src_subject_id','interview_age','parentPcount','Grades','income','sex','race_ethnicity','matched_group','eventname')
# eliminate rows with NAs and ensure none without two-timepoint data
# variables of interest redux
masterdf=masterdf[,c(variablesOfInterest)]
# na omitted version
masterdf=masterdf[rowSums(is.na(masterdf)) == 0, ] 
print(dim(masterdf))
# and two-timepoint check
twoTPsubjs=names(table(masterdf$src_subject_id)[table(masterdf$src_subject_id)>1])
masterdf=masterdf[masterdf$subj %in% twoTPsubjs,]

# now set subsets to use for temporal precedence analyses 
df1=masterdf[masterdf$eventname=='baseline_year_1_arm_1',]
df2=masterdf[masterdf$eventname=='2_year_follow_up_y_arm_1',]
subsetOfBoth=merge(df1,df2,by='src_subject_id')
subsetOfBoth=subsetOfBoth$src_subject_id

# convert to one row per subj for temporal precedence analyses
OutDFTmpPrec<-merge(df1,df2,by='src_subject_id')
print(dim(OutDFTmpPrec))

# save it out
saveRDS(OutDFTmpPrec,'~/OutDFTmpPrec.rds')
```

```{r}
# basic t-test for boys vs. girls: baseline
bBV=subset(df1,sex=="M")
gBV=subset(df1,sex=="F")
t.test(bBV$cbcl_scr_syn_totprob_r,gBV$cbcl_scr_syn_totprob_r)
# basic t-test for boys vs. girls: 2-years
b2=subset(df2,sex=="M")
g2=subset(df2,sex=="F")
t.test(b2$cbcl_scr_syn_totprob_r,g2$cbcl_scr_syn_totprob_r)
# and by poverty status # new subsetting
masterdf$poverty=0
masterdf$income<-as.numeric(masterdf$income)
# note that poverty is defined as income < 5: https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups
masterdf$poverty[masterdf$income<5]=1
masterdf$poverty=as.ordered(masterdf$poverty)
df1=masterdf[masterdf$eventname=='baseline_year_1_arm_1',]
df2=masterdf[masterdf$eventname=='2_year_follow_up_y_arm_1',]
# now divide
pBV=subset(df1,poverty==1)
npBV=subset(df1,poverty==0)
t.test(pBV$cbcl_scr_syn_totprob_r,npBV$cbcl_scr_syn_totprob_r)
# basic t-test for boys vs. girls: 2-years
p2=subset(df2,poverty==1)
np2=subset(df2,poverty==0)
t.test(p2$cbcl_scr_syn_totprob_r,np2$cbcl_scr_syn_totprob_r)
```
