---
title: "Figure3"
output: github_document
date: "2023-05-06"
---

```{r}
# figure 3
library(mgcv)
library(visreg)
library(gratia)
library(dplyr)
library(tidyr)
library(stringr)
library(data.table)
library(ggridges)
library(ggbeeswarm)
library(ggExtra)
```

```{r}
# set functions
plot_bootstraps <- function(data,maxval,Name,maxValuePlot,BorderlineClinical,Clinical) {
  # Melt the data frame
  data_melt <- melt(t(data))
  data_melt$Var1 <- rep(seq(1, maxval), nrow(data))

  # Calculate percentiles
  percentiles <- data %>%
    summarise(across(everything(), quantile, probs = c(0.01, 0.99), na.rm = TRUE))
  
  percentiles_long <- tidyr::pivot_longer(percentiles, cols = everything(), names_to = "Percentile", values_to = "YValue")

  # Add CI column
  data_melt$CI <- 0
  
  # Prepare CIs for insertion
  CIs <- data.frame(rep(seq(1, maxval), 2), c(rep(10001, maxval), rep(10002, maxval)), percentiles_long$YValue, rep(1, (maxval*2)))
  colnames(CIs) <- colnames(data_melt)
  
  # Add CIs
  data_melt2 <- rbind(data_melt, CIs)
  
  # Convert CI column to factor
  data_melt2$CI <- as.factor(data_melt2$CI)
  
  # Plotting the lines
  ggplot(data = data_melt2, aes(x = Var1, y = value, group = Var2, color = Var2)) +
    geom_line(aes(alpha = CI), show.legend = FALSE) +
    scale_color_viridis_c(option = "inferno", direction = -1) +
    scale_alpha_manual(values = c(0.01, 1), guide = FALSE) + ylim(c(-1.5,1.5)) +
    theme_minimal(base_size=35) + 
    ylab(expression(italic(g)))+xlab(Name)+
    geom_vline(xintercept = BorderlineClinical, linetype = "dashed")+
    geom_vline(xintercept = Clinical, linetype = "dashed")+
    theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,maxValuePlot),expand = expansion(mult = c(0, 0)))
}

find_furthest_nonzero <- function(data) {
  numZeros=colSums(data==0)
  isZeroZeros=numZeros==0
  furthest_nonzero=sum(isZeroZeros)
}

# set colors
my_palette <- colorRampPalette(colors = c("#051099", "#1d5cb7", "white", "#e41a1c", "#a80009"))

```


```{r}
# load in fits: ordered as follows:
# F_pFit,F_intFit,F_extFit,M_pFit,M_intFit,M_extFit,P_pFit,P_intFit,P_extFit,R_pFit,R_intFit,R_extFit,PF_pFit,PF_intFit,PF_extFit,PM_pFit,PM_intFit,PM_extFit,RM_pFit,RM_intFit,RM_extFit,RF_pFit,RF_intFit,RF_extFit
Fits=readRDS('~/Desktop/g_p/F3_gpFits.rds')
#Derivs=
# pull clinical cutoff from master df: t scores > 68 = borderline clinical, 70 = clinical
masterdfP_bc<-masterdf[masterdf$cbcl_scr_syn_totprob_t==68,]
masterdfP_c<-masterdf[masterdf$cbcl_scr_syn_totprob_t==70,]
masterdfI_bc<-masterdf[masterdf$cbcl_scr_syn_internal_t==68,]
masterdfI_c<-masterdf[masterdf$cbcl_scr_syn_internal_t==70,]
masterdfE_bc<-masterdf[masterdf$cbcl_scr_syn_external_t==68,]
masterdfE_c<-masterdf[masterdf$cbcl_scr_syn_external_t==70,]

# borderline clinical and clinical cutoffs
Pbc=mean(masterdfP_bc$cbcl_scr_syn_totprob_r)
Pc=mean(masterdfP_c$cbcl_scr_syn_totprob_r)
Ibc=mean(masterdfP_bc$cbcl_scr_syn_internal_r)
Ic=mean(masterdfP_c$cbcl_scr_syn_internal_r)
Ebc=mean(masterdfE_bc$cbcl_scr_syn_external_r)
Ec=mean(masterdfE_c$cbcl_scr_syn_external_r)
```

```{r}
# isolate Female, Male, Poor, Rich
F_PFits=Fits[,1:161]
F_IFits=Fits[,162:212]
F_EFits=Fits[,213:259]

# calculate some background info for plots
MaxP=find_furthest_nonzero(F_PFits)
MaxI=find_furthest_nonzero(F_IFits)
MaxE=find_furthest_nonzero(F_EFits)

# get median value
F_PFits_Coverage=F_PFits[,seq(1:MaxP)]
col_means=colMeans(F_PFits_Coverage)
FP_medians <- apply(F_PFits_Coverage, 2, median)

# get median internalizing
F_IFits_Coverage=F_IFits[,seq(1:MaxI)]
col_means=colMeans(F_IFits_Coverage)
FI_medians <- apply(F_IFits_Coverage, 2, median)

# get median externalizing
F_EFits_Coverage=F_EFits[,seq(1:MaxE)]
col_means=colMeans(F_EFits_Coverage)
FE_medians <- apply(F_EFits_Coverage, 2, median)

# plot equiv derivs
#positive_counts <- colSums(AnxFits > 0, na.rm = TRUE)
#negative_counts <- colSums(AnxFits < 0, na.rm = TRUE)
#positive_countsSig=positive_counts>9900
#negative_countsSig=negative_counts>9900
#data <- apply(AnxFits, 2, function(x) quantile(x, probs = 0.5))
#dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
#dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
#dervPlotDf$sig_deriv=0
#dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
#dervPlotDf$seq=1:(dim(dervPlotDf)[1])
#ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
#    theme(panel.spacing = unit(-.01,"cm")) +
#    scale_fill_gradient2(low = "#377eb8", midpoint = 0, mid = "white",
#    high = "#e41a1c",limits = c(min(-.075),max(0.075)))+theme_minimal(base_size = 35)+
#    xlim(c(0,MaxAnx))+xlab('Anx.Depr.')+
#    guides(fill=FALSE)+
#    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
#    scale_x_continuous(limits = c(0,MaxAnx),expand = expansion(mult = c(0, 0)))
#
```

```{r}
# isolate male fits
M_PFits=Fits[,260:420]
M_IFits=Fits[,421:471]
M_EFits=Fits[,472:518]

# calculate some background info for plots
MaxP=find_furthest_nonzero(M_PFits)
MaxI=find_furthest_nonzero(M_IFits)
MaxE=find_furthest_nonzero(M_EFits)

# get mean median value
M_PFits_Coverage=M_PFits[,seq(1:MaxP)]
col_means=colMeans(M_PFits_Coverage)
MP_medians <- apply(M_PFits_Coverage, 2, median)


# get mean median value
M_IFits_Coverage=M_IFits[,seq(1:MaxI)]
col_means=colMeans(M_IFits_Coverage)
MI_medians <- apply(M_IFits_Coverage, 2, median)

# get mean median value
M_EFits_Coverage=M_EFits[,seq(1:MaxE)]
col_means=colMeans(M_EFits_Coverage)
ME_medians <- apply(M_EFits_Coverage, 2, median)

data <- data.frame(
  x = 1:length(FP_medians),
  y_girls = FP_medians,
  y_boys = MP_medians
)

# Create the line plot for p
ggplot(data, aes(x = x, y = y_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = y_boys), color = "#EFC570", size = 1.5) +
  labs(x = expression(italic(p)), y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Pbc, linetype = "dashed")+
  geom_vline(xintercept = Pc, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

data <- data.frame(
  x = 1:length(FI_medians),
  y_girls = FI_medians,
  y_boys = MI_medians
)

# Create the line plot for int
ggplot(data, aes(x = x, y = y_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = y_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Internalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))


data <- data.frame(
  x = 1:length(FE_medians),
  y_girls = FE_medians,
  y_boys = ME_medians
)

# Create the line plot for ext
ggplot(data, aes(x = x, y = y_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = y_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Externalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

```

```{r}
# and derivatives
# Create an empty matrix to store the derivatives
F_P_derivative_matrix <- matrix(0, nrow = nrow(F_PFits), ncol = ncol(F_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(F_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- F_PFits[, i + 1] - F_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  F_P_derivative_matrix[, i] <- derivatives
}

# Create an empty matrix to store the derivatives
M_P_derivative_matrix <- matrix(0, nrow = nrow(M_PFits), ncol = ncol(M_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(F_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- M_PFits[, i + 1] - M_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  M_P_derivative_matrix[, i] <- derivatives
}

# calc sig dervs
# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(F_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(F_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(F_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Girl P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(M_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(M_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(M_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Boy P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

```

```{r}
# Create an empty matrix to store the derivatives
F_I_derivative_matrix <- matrix(0, nrow = nrow(F_IFits), ncol = ncol(F_IFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(F_IFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- F_IFits[, i + 1] - F_IFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  F_I_derivative_matrix[, i] <- derivatives
}

# Create an empty matrix to store the derivatives
M_I_derivative_matrix <- matrix(0, nrow = nrow(M_IFits), ncol = ncol(M_IFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(M_IFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- M_IFits[, i + 1] - M_IFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  M_I_derivative_matrix[, i] <- derivatives
}

# calc sig dervs
# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(F_I_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(F_I_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(F_I_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxI))+xlab('Girl Int.')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxI),expand = expansion(mult = c(0, 0)))

# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(M_I_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(M_I_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(M_I_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxI))+xlab('Boy Int.')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxI),expand = expansion(mult = c(0, 0)))

```

```{r}
# Create an empty matrix to store the derivatives
F_E_derivative_matrix <- matrix(0, nrow = nrow(F_EFits), ncol = ncol(F_EFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(F_EFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- F_EFits[, i + 1] - F_EFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  F_E_derivative_matrix[, i] <- derivatives
}

# Create an empty matrix to store the derivatives
M_E_derivative_matrix <- matrix(0, nrow = nrow(M_EFits), ncol = ncol(M_EFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(M_EFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- M_EFits[, i + 1] - M_EFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  M_E_derivative_matrix[, i] <- derivatives
}

# calc sig dervs
# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(F_E_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(F_E_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(F_E_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxE))+xlab('Girl Ext.')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxE),expand = expansion(mult = c(0, 0)))

# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(M_E_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(M_E_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(M_E_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxE))+xlab('Boy Ext.')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxE),expand = expansion(mult = c(0, 0)))

```

```{r}
# max girl boy plots for above poverty line and below poverty line plots for p, int, and ext

# isolate fits to children below poverty line
P_PFits=Fits[,519:679]
P_IFits=Fits[,680:730]
P_EFits=Fits[,731:777]

# calculate some background info for plots
MaxP=find_furthest_nonzero(P_PFits)
MaxI=find_furthest_nonzero(P_IFits)
MaxE=find_furthest_nonzero(P_EFits)


```

```{r}
# children above poverty line
R_PFits=Fits[,778:938]
R_IFits=Fits[,939:989]
R_EFits=Fits[,990:1036]

# calculate some background info for plots
MaxP=find_furthest_nonzero(R_PFits)
MaxI=find_furthest_nonzero(R_IFits)
MaxE=find_furthest_nonzero(R_EFits)

```

```{r}
# now from the interactions: girls below poverty line first
PF_PFits=Fits[,1037:1197]
PF_IFits=Fits[,1198:1248]
PF_EFits=Fits[,1249:1295]

# calculate some background info for plots
MaxP=find_furthest_nonzero(PF_PFits)
MaxI=find_furthest_nonzero(PF_IFits)
MaxE=find_furthest_nonzero(PF_EFits)

# get median values
PF_PFits_Coverage=PF_PFits[,1:MaxP]
PF_IFits_Coverage=PF_IFits[,1:MaxI]
PF_EFits_Coverage=PF_EFits[,1:MaxE]
PF_p_median=apply(PF_PFits_Coverage,2,median)
PF_Int_median=apply(PF_IFits_Coverage,2,median)
PF_Ext_median=apply(PF_EFits_Coverage,2,median)

```

```{r}
# now boys below the poverty line
PM_PFits=Fits[,1296:1456]
PM_IFits=Fits[,1457:1507]
PM_EFits=Fits[,1508:1554]

# calculate some background info for plots
MaxP=find_furthest_nonzero(PM_PFits)
MaxI=find_furthest_nonzero(PM_IFits)
MaxE=find_furthest_nonzero(PM_EFits)

# get median values
PM_PFits_Coverage=PM_PFits[,1:MaxP]
PM_IFits_Coverage=PM_IFits[,1:MaxI]
PM_EFits_Coverage=PM_EFits[,1:MaxE]
PM_p_median=apply(PM_PFits_Coverage,2,median)
PM_Int_median=apply(PM_IFits_Coverage,2,median)
PM_Ext_median=apply(PM_EFits_Coverage,2,median)

```

```{r}
# girls above poverty line
RF_PFits=Fits[,1814:1974]
RF_IFits=Fits[,1975:2025]
RF_EFits=Fits[,2026:2072]

# calculate some background info for plots
MaxP=find_furthest_nonzero(RF_PFits)
MaxI=find_furthest_nonzero(RF_IFits)
MaxE=find_furthest_nonzero(RF_EFits)

# get median values
RF_PFits_Coverage=RF_PFits[,1:MaxP]
RF_IFits_Coverage=RF_IFits[,1:MaxI]
RF_EFits_Coverage=RF_EFits[,1:MaxE]
RF_p_median=apply(RF_PFits_Coverage,2,median)
RF_Int_median=apply(RF_IFits_Coverage,2,median)
RF_Ext_median=apply(RF_EFits_Coverage,2,median)

```


```{r}
# boys above poverty line
RM_PFits=Fits[,1555:1715]
RM_IFits=Fits[,1716:1766]
RM_EFits=Fits[,1767:1813]

# calculate some background info for plots
MaxP=find_furthest_nonzero(RM_PFits)
qMaxI=find_furthest_nonzero(RM_IFits)
MaxE=find_furthest_nonzero(RM_EFits)

# get median values
RM_PFits_Coverage=RM_PFits[,1:MaxP]
RM_IFits_Coverage=RM_IFits[,1:MaxI]
RM_EFits_Coverage=RM_EFits[,1:MaxE]
RM_p_median=apply(RM_PFits_Coverage,2,median)
RM_Int_median=apply(RM_IFits_Coverage,2,median)
RM_Ext_median=apply(RM_EFits_Coverage,2,median)

```

```{r}
# get derivatives for above and below poverty line for girls and boys for p
# and derivatives
# Create an empty matrix to store the derivatives
RF_P_derivative_matrix <- matrix(0, nrow = nrow(RF_PFits), ncol = ncol(RF_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(RF_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- RF_PFits[, i + 1] - RF_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  RF_P_derivative_matrix[, i] <- derivatives
}

# Create an empty matrix to store the derivatives
RM_P_derivative_matrix <- matrix(0, nrow = nrow(RM_PFits), ncol = ncol(RM_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(RM_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- RM_PFits[, i + 1] - RM_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  RM_P_derivative_matrix[, i] <- derivatives
}

# calc sig dervs
# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(RF_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(RF_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(RF_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Girl P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(RM_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(RM_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(RM_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Boy P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

# ∆∆∆∆∆∆∆∆∆∆
# for poverty
# ∆∆∆∆∆∆∆∆∆∆

# get derivatives for above and below poverty line for girls and boys for p
# and derivatives
# Create an empty matrix to store the derivatives
PF_P_derivative_matrix <- matrix(0, nrow = nrow(PF_PFits), ncol = ncol(PF_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(PF_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- PF_PFits[, i + 1] - PF_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  PF_P_derivative_matrix[, i] <- derivatives
}

# Create an empty matrix to store the derivatives
PM_P_derivative_matrix <- matrix(0, nrow = nrow(PM_PFits), ncol = ncol(PM_PFits) - 1)

# Calculate the derivative for each column
for (i in 1:(ncol(PM_PFits) - 1)) {
  # Calculate the differences in x (assuming a constant difference)
  dx <- 1
  # Calculate the differences in y (predicted values)
  dy <- PM_PFits[, i + 1] - PM_PFits[, i]
  # Calculate the derivatives (slopes)
  derivatives <- dy / dx
  # Store the derivatives in the derivative matrix
  PM_P_derivative_matrix[, i] <- derivatives
}

# calc sig dervs
# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(PF_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(PF_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(PF_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Girl P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

# get straightfoward of segment where 99% is over 0 or under
positive_counts <- colSums(PM_P_derivative_matrix > 0, na.rm = TRUE)
negative_counts <- colSums(PM_P_derivative_matrix < 0, na.rm = TRUE)
# find where each is 99% or greater
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
# make dataframe: 50th percentile of derivatives accompanied by posSig and NegSig vector
data <- apply(PM_P_derivative_matrix, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
# if either is sig at 99% plot
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
# use it to mask calculated derivs
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Boy P')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))


# now plot two panels for p, one for girl boy below poverty line and one above. physically place above poverty line above the below poverty line plot
data_pov <- data.frame(
  x = 1:length(PF_p_median),
  pov_girls = PF_p_median,
  pov_boys = PM_p_median
)

data_nopov <- data.frame(
  x = 1:length(PF_p_median),
  r_girls = RF_p_median,
  r_boys = RM_p_median
)

# Create the line plot for p for poverty
plot1<-ggplot(data_pov, aes(x = x, y = pov_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = pov_boys), color = "#EFC570", size = 1.5) +
  labs(x = expression(italic(p)), y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Pbc, linetype = "dashed")+
  geom_vline(xintercept = Pc, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

# Create the line plot for p for above poverty line
plot2<-ggplot(data_nopov, aes(x = x, y = r_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = r_boys), color = "#EFC570", size = 1.5) +
  labs(x = expression(italic(p)), y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Pbc, linetype = "dashed")+
  geom_vline(xintercept = Pc, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

# create the line plot for int for poverty
data_pov <- data.frame(
  x = 1:length(PF_Int_median),
  pov_girls = PF_Int_median,
  pov_boys = PM_Int_median
)

data_nopov <- data.frame(
  x = 1:length(RF_Int_median),
  r_girls = RF_Int_median,
  r_boys = RM_Int_median
)


plot1<-ggplot(data_pov, aes(x = x, y = pov_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = pov_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Internalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

# creaete the line plot for int for above poverty line
plot2<-ggplot(data_nopov, aes(x = x, y = r_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = r_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Internalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

# create the line plot for ext for poverty
data_pov <- data.frame(
  x = 1:length(PF_Ext_median),
  pov_girls = PF_Ext_median,
  pov_boys = PM_Ext_median
)

data_nopov <- data.frame(
  x = 1:length(RF_Ext_median),
  r_girls = RF_Ext_median,
  r_boys = RM_Ext_median
)


plot1<-ggplot(data_pov, aes(x = x, y = pov_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = pov_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Externalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))

# creaete the line plot for int for above poverty line
plot2<-ggplot(data_nopov, aes(x = x, y = r_girls)) +
  geom_line(color = "#9589BF", size = 1.5) +
  geom_line(aes(y = r_boys), color = "#EFC570", size = 1.5) +
  labs(x = "Externalizing", y = expression(italic(g))) +
  theme_minimal(base_size = 35) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "top",
        legend.title = element_blank(),
        legend.background = element_rect(fill = "white"))+ylim(-1.5,1.5)+
  geom_vline(xintercept = Ibc, linetype = "dashed")+
  geom_vline(xintercept = Ic, linetype = "dashed")+
        theme(panel.border = element_rect(color = "black", fill = NA, size = 1))


```


```{r}
# now plot derivatives

# NEED TO CHANGE TO EXTRACT DERIVATIVES MANUALLY
#Fits=readRDS('~/Desktop/g_p/F3_gpDerivs.rds')

F_PFits=Fits[,1:161]
F_IFits=Fits[,162:212]
F_EFits=Fits[,213:259]

M_PFits=Fits[,260:420]
M_IFits=Fits[,421:471]
M_EFits=Fits[,472:518]


# for girl fits p
positive_counts <- colSums(F_EFits > 0, na.rm = TRUE)
negative_counts <- colSums(F_EFits < 0, na.rm = TRUE)
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
data <- apply(F_EFits, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Girls')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))

# boys p
positive_counts <- colSums(M_EFits > 0, na.rm = TRUE)
negative_counts <- colSums(M_EFits < 0, na.rm = TRUE)
positive_countsSig=positive_counts>9900
negative_countsSig=negative_counts>9900
data <- apply(M_EFits, 2, function(x) quantile(x, probs = 0.5))
dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
dervPlotDf$sig_deriv=0
dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
dervPlotDf$seq=1:(dim(dervPlotDf)[1])
ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
    theme(panel.spacing = unit(-.01,"cm")) +
    scale_fill_gradientn(colors = my_palette(100),limits = c(min(-.25),max(0.25)))+theme_minimal(base_size = 35)+
    xlim(c(0,MaxP))+xlab('Boys')+
    guides(fill=FALSE)+
    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,MaxP),expand = expansion(mult = c(0, 0)))
```

```{r}
# grades plots from master df
grade_levels <- c(5, 4, 3, 2, 1)
grade_labels <- c("F", "Failing", "C", "B", "A")
masterdf$plotGrades<-factor(masterdf$Grades, levels = grade_levels, labels = grade_labels)
masterdf$plotGrades[masterdf$plotGrades=="F"]="Failing"
# only 28 f's: merge into Ds
boys_data <- subset(masterdf, sex == "M")
girls_data <- subset(masterdf, sex == "F")

# plot girls
girlsWealth=subset(girls_data, income >5)
girlsPoor=subset(masterdf, income <5)
ggplot(girlsWealth, aes(x = cbcl_scr_syn_totprob_r, y = plotGrades)) +
  geom_boxplot(fill="#9589BF") +
  labs(title = "Girls above poverty line",
       x = expression(italic(p)),
       y = "Grades")+theme_minimal(base_size=25)+xlim(0,113)+
      geom_vline(xintercept = Pbc, linetype = "dashed")+
      geom_vline(xintercept = Pc, linetype = "dashed")

ggplot(girlsPoor, aes(x = cbcl_scr_syn_totprob_r, y = plotGrades)) +
  geom_boxplot(fill="#9589BF") +
  labs(title = "Girls below poverty line",
       x = expression(italic(p)),
       y = "Grades")+theme_minimal(base_size=25)+xlim(0,113)+
      geom_vline(xintercept = Pbc, linetype = "dashed")+
      geom_vline(xintercept = Pc, linetype = "dashed")
  
# plot boys
boysWealth=subset(boys_data, income >5)
boysPoor=subset(boys_data, income <5)
# Create the box plot for boys
ggplot(boysWealth, aes(x = cbcl_scr_syn_totprob_r, y = plotGrades)) +
  geom_boxplot(fill="#EFC570") +
  labs(title = "Boys above poverty line",
       x = expression(italic(p)),
       y = "Grades")+theme_minimal(base_size=25)+xlim(0,113)+
      geom_vline(xintercept = Pbc, linetype = "dashed")+
      geom_vline(xintercept = Pc, linetype = "dashed")

ggplot(boysPoor, aes(x = cbcl_scr_syn_totprob_r, y = plotGrades)) +
  geom_boxplot(fill="#EFC570")+
  labs(title = "Boys below poverty line",
       x = expression(italic(p)),
       y = "Grades")+theme_minimal(base_size=25)+xlim(0,113)+
      geom_vline(xintercept = Pbc, linetype = "dashed")+
      geom_vline(xintercept = Pc, linetype = "dashed")
```


```{r}
# deviance explained plots
DevExpl=readRDS('~/Desktop/g_p/F3-5DevExpl.rds')
DevExpl_L=readRDS('~/Desktop/g_p/F3-5DevExpl_longit.rds')
DevExpl_L_Relative=DevExpl_L-DevExpl_L[,1]
DevExpl=DevExpl[,c(1,3,4,6)]
DevExpl_L_Relative=DevExpl_L_Relative[,c(2,4,5,7)]

df_long <- reshape2::melt(DevExpl)
custom_labels <- c(expression(italic(g)), "Grades", expression(paste(italic(g), " + Parental ", italic("p"))),expression(paste("Grades + Parental ", italic("p"))))
# Create the boxplot - 1350 x 800 dimensions
ggplot(df_long, aes(x = variable, y = value)) +
  geom_boxplot() +
  xlab("Variables") +
  scale_x_discrete(labels = custom_labels) +
  ylab("Cross-sectional Deviance Explained") + theme_minimal(base_size=30)

# now for longitudinal variables
custom_labels <- c(expression(italic(g)), "Grades", expression(paste(italic(g), " + Parental ", italic("p"))),expression(paste("Grades + Parental ", italic("p"))))
df_long <- reshape2::melt(DevExpl_L_Relative)
# Create the boxplot
ggplot(df_long, aes(x = variable, y = value)) +
  geom_boxplot() +
  xlab("Variables") +
  scale_x_discrete(labels = custom_labels) +
  ylab("Longitudinal Deviance Explained") + theme_minimal(base_size=30)
```

```{r}
# SUPPLEMENT

# grades plots from master df
grade_levels <- c(5, 4, 3, 2, 1)
grade_labels <- c("F", "Failing", "C", "B", "A")
masterdf$plotGrades<-factor(masterdf$Grades, levels = grade_levels, labels = grade_labels)
masterdf$plotGrades[masterdf$plotGrades=="F"]="Failing"
plotdf=masterdf[,c('plotGrades','g')]
### supplementary grades fig
ggplot(plotdf, aes(x = g, y = plotGrades)) +
  geom_boxplot() +
  labs(title = "All Children",
       x = expression(italic(g)),
       y = "Grades")+theme_minimal(base_size=25)+xlim(-4,4.6)

# poverty plots from master df
masterdf$income<-as.numeric(masterdf$income)
# note that poverty is defined as income < 5: https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups
masterdf$poverty=0
masterdf$poverty[masterdf$income<5]=1
masterdf$poverty=as.ordered(masterdf$poverty)
pov_labels <- c("Above Poverty Line", "Below")
masterdf$poverty<-factor(masterdf$poverty, labels = pov_labels)
# for cats probably not needed
library(forcats)
masterdf$poverty <- fct_relevel(masterdf$poverty, "Below")
plotdf=masterdf[,c('poverty','cbcl_scr_syn_totprob_r')]
### supplementary grades fig
ggplot(plotdf, aes(x = cbcl_scr_syn_totprob_r, y = poverty)) +
  geom_boxplot() +
  labs(title = "All Children",
       x = expression(italic(p)),
       y = "Parental Income")+theme_minimal(base_size=25)

```








```{r}
#### TEMPORAL PRECEDENCE TABLE
library(mgcv)
# load temporal precedence data from SampleConstruction.Rmd
tpdf=readRDS('~/OutDFTmpPrec.rds')

```

```{r}
# Load the "lavaan" package
library(lavaan)


# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_totprob_r.y ~ cbcl_scr_syn_totprob_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_totprob_r.x
  cbcl_scr_syn_totprob_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_totprob_r.x
  g.y ~~ cbcl_scr_syn_totprob_r.y
  
  # Residual variances
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_totprob_r.x ~~ cbcl_scr_syn_totprob_r.x
  cbcl_scr_syn_totprob_r.y ~~ cbcl_scr_syn_totprob_r.y
'

# Fit the model to the data using maximum likelihood estimation
pfit <- sem(model, data = tpdf)

# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_internal_r.y ~ cbcl_scr_syn_internal_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_internal_r.x
  cbcl_scr_syn_internal_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_internal_r.x
  g.y ~~ cbcl_scr_syn_internal_r.y
  
  # Residual variances
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_internal_r.x ~~ cbcl_scr_syn_internal_r.x
  cbcl_scr_syn_internal_r.y ~~ cbcl_scr_syn_internal_r.y
'

# Fit the model to the data using maximum likelihood estimation
ifit <- sem(model, data = tpdf)

# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_external_r.y ~ cbcl_scr_syn_external_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_external_r.x
  cbcl_scr_syn_external_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_external_r.x
  g.y ~~ cbcl_scr_syn_external_r.y
  
  # Residual variances
  # note this tracks concurrent increases in outcome variables
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_external_r.x ~~ cbcl_scr_syn_external_r.x
  cbcl_scr_syn_external_r.y ~~ cbcl_scr_syn_external_r.y
'

# Fit the model to the data using maximum likelihood estimation
efit <- sem(model, data = tpdf)

```

```{r}
# supplemental poverty analysis
povBoots=readRDS('~/Desktop/g_p/F3_gpPovNonPov2k.rds')
# 2k version
povBoots=povBoots[1:2000,]

```


