---
title: "FIgure2"
output: github_document
date: "2023-05-06"
---

```{r}
# figure 2
library(mgcv)
library(visreg)
library(gratia)
library(dplyr)
library(tidyr)
library(stringr)
library(data.table)
library(ggridges)
library(ggbeeswarm)
```

```{r}
# set functions
plot_bootstraps <- function(data,maxval,Name,maxValuePlot,BorderlineClinical,Clinical) {
  # Melt the data frame
  data_melt <- melt(t(data))
  data_melt$Var1 <- rep(seq(1, maxval), nrow(data))

  # Calculate percentiles
  percentiles <- data %>%
    summarise(across(everything(), quantile, probs = c(0.01, 0.99), na.rm = TRUE))
  
  percentiles_long <- tidyr::pivot_longer(percentiles, cols = everything(), names_to = "Percentile", values_to = "YValue")

  # Add CI column
  data_melt$CI <- 0
  
  # Prepare CIs for insertion
  CIs <- data.frame(rep(seq(1, maxval), 2), c(rep(10001, maxval), rep(10002, maxval)), percentiles_long$YValue, rep(1, (maxval*2)))
  colnames(CIs) <- colnames(data_melt)
  
  # Add CIs
  data_melt2 <- rbind(data_melt, CIs)
  
  # Convert CI column to factor
  data_melt2$CI <- as.factor(data_melt2$CI)
  
  # Plotting the lines
  ggplot(data = data_melt2, aes(x = Var1, y = value, group = Var2, color = Var2)) +
    geom_line(aes(alpha = CI), show.legend = FALSE) +
    scale_color_viridis_c(option = "inferno", direction = -1) +
    scale_alpha_manual(values = c(0.01, 1), guide = FALSE) + ylim(c(-1.5,1.5)) +
    theme_minimal(base_size=35) + 
    ylab(expression(italic(g)))+xlab(Name)+
    geom_vline(xintercept = BorderlineClinical, linetype = "dashed")+
    geom_vline(xintercept = Clinical, linetype = "dashed")+
    theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
    scale_x_continuous(limits = c(0,maxValuePlot),expand = expansion(mult = c(0, 0)))
}

find_furthest_nonzero <- function(data) {
  numZeros=colSums(data==0)
  isZeroZeros=numZeros==0
  furthest_nonzero=sum(isZeroZeros)
}
```

```{r}

```











```{r}
# load in fits: ordered as follows:
# F_pFit,F_intFit,F_extFit,M_pFit,M_intFit,M_extFit,P_pFit,P_intFit,P_extFit,R_pFit,R_intFit,R_extFit,PF_pFit,PF_intFit,PF_extFit,PM_pFit,PM_intFit,PM_extFit,RM_pFit,RM_intFit,RM_extFit,RF_pFit,RF_intFit,RF_extFit
Fits=readRDS('~/Desktop/g_p/F3_gpFits.rds')
Derivs=
# pull clinical cutoff from master df: t scores > 68 = borderline clinical, 70 = clinical
masterdfP_bc<-masterdf[masterdf$cbcl_scr_syn_totprob_t==68,]
masterdfP_c<-masterdf[masterdf$cbcl_scr_syn_totprob_t==70,]
masterdfI_bc<-masterdf[masterdf$cbcl_scr_syn_internal_t==68,]
masterdfI_c<-masterdf[masterdf$cbcl_scr_syn_internal_t==70,]
masterdfE_bc<-masterdf[masterdf$cbcl_scr_syn_external_t==68,]
masterdfE_c<-masterdf[masterdf$cbcl_scr_syn_external_t==70,]

# borderline clinical and clinical cutoffs
Pbc=mean(masterdfP_bc$cbcl_scr_syn_totprob_r)
Pc=mean(masterdfP_c$cbcl_scr_syn_totprob_r)
Ibc=mean(masterdfP_bc$cbcl_scr_syn_internal_r)
Ic=mean(masterdfP_c$cbcl_scr_syn_internal_r)
Ebc=mean(masterdfE_bc$cbcl_scr_syn_external_r)
Ec=mean(masterdfE_c$cbcl_scr_syn_external_r)
```

```{r}
# isolate Female, Male, Poor, Rich
F_PFits=Fits[,1:161]
F_IFits=Fits[,162:212]
F_EFits=Fits[,213:259]

# calculate some background info for plots
MaxP=find_furthest_nonzero(F_PFits)
MaxI=find_furthest_nonzero(IFits)
MaxE=find_furthest_nonzero(F_IFits)

plot_bootstraps(F_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(F_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(F_EFits,47,'externalizing',MaxE,Ebc,Ec)

# plot equiv derivs
#positive_counts <- colSums(AnxFits > 0, na.rm = TRUE)
#negative_counts <- colSums(AnxFits < 0, na.rm = TRUE)
#positive_countsSig=positive_counts>9900
#negative_countsSig=negative_counts>9900
#data <- apply(AnxFits, 2, function(x) quantile(x, probs = 0.5))
#dervPlotDf<-data.frame(data,positive_countsSig,negative_countsSig)
#dervPlotDf$sig_derivMask=dervPlotDf[,2]+dervPlotDf[,3]>0
#dervPlotDf$sig_deriv=0
#dervPlotDf$sig_deriv[dervPlotDf$sig_derivMask]=dervPlotDf$data[dervPlotDf$sig_derivMask]
#dervPlotDf$seq=1:(dim(dervPlotDf)[1])
#ggplot(data=dervPlotDf) + geom_raster(aes(x = seq, y = .5, fill = sig_deriv))+
#    theme(panel.spacing = unit(-.01,"cm")) +
#    scale_fill_gradient2(low = "#377eb8", midpoint = 0, mid = "white",
#    high = "#e41a1c",limits = c(min(-.075),max(0.075)))+theme_minimal(base_size = 35)+
#    xlim(c(0,MaxAnx))+xlab('Anx.Depr.')+
#    guides(fill=FALSE)+
#    theme(axis.title.y = element_blank(),axis.text.y=element_blank())+theme(panel.border = element_rect(color = "black", fill = NA, size = 1))+
#    scale_x_continuous(limits = c(0,MaxAnx),expand = expansion(mult = c(0, 0)))
#
```

```{r}
# isolate male fits
M_PFits=Fits[,260:420]
M_IFits=Fits[,421:471]
M_EFits=Fits[,472:518]

# calculate some background info for plots
MaxP=find_furthest_nonzero(M_PFits)
MaxI=find_furthest_nonzero(M_IFits)
MaxE=find_furthest_nonzero(M_EFits)

plot_bootstraps(M_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(M_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(M_EFits,47,'externalizing',MaxE,Ebc,Ec)

```

```{r}
# isolate fits to children below poverty line
P_PFits=Fits[,519:679]
P_IFits=Fits[,680:730]
P_EFits=Fits[,731:777]

# calculate some background info for plots
MaxP=find_furthest_nonzero(P_PFits)
MaxI=find_furthest_nonzero(P_IFits)
MaxE=find_furthest_nonzero(P_EFits)

plot_bootstraps(P_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(P_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(P_EFits,47,'externalizing',MaxE,Ebc,Ec)

```

```{r}
# children above poverty line
R_PFits=Fits[,778:938]
R_IFits=Fits[,939:989]
R_EFits=Fits[,990:1036]

# calculate some background info for plots
MaxP=find_furthest_nonzero(R_PFits)
MaxI=find_furthest_nonzero(R_IFits)
MaxE=find_furthest_nonzero(R_EFits)

plot_bootstraps(R_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(R_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(R_EFits,47,'externalizing',MaxE,Ebc,Ec)

```

```{r}
# now from the interactions: girls below poverty line first
PF_PFits=Fits[,1037:1197]
PF_IFits=Fits[,1198:1248]
PF_EFits=Fits[,1249:1295]

# calculate some background info for plots
MaxP=find_furthest_nonzero(PF_PFits)
MaxI=find_furthest_nonzero(PF_IFits)
MaxE=find_furthest_nonzero(PF_EFits)

plot_bootstraps(PF_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(PF_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(PF_EFits,47,'externalizing',MaxE,Ebc,Ec)

```

```{r}
# now boys below the poverty line
PM_PFits=Fits[,1296:1456]
PM_IFits=Fits[,1457:1507]
PM_EFits=Fits[,1508:1554]

# calculate some background info for plots
MaxP=find_furthest_nonzero(PM_PFits)
MaxI=find_furthest_nonzero(PM_IFits)
MaxE=find_furthest_nonzero(PM_EFits)

plot_bootstraps(PM_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(PM_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(PM_EFits,47,'externalizing',MaxE,Ebc,Ec)

```

```{r}
# girls above poverty line
RF_PFits=Fits[,1555:1715]
RF_IFits=Fits[,1716:1766]
RF_EFits=Fits[,1767:1813]

# calculate some background info for plots
MaxP=find_furthest_nonzero(RF_PFits)
MaxI=find_furthest_nonzero(RF_IFits)
MaxE=find_furthest_nonzero(RF_EFits)

plot_bootstraps(RF_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(RF_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(RF_EFits,47,'externalizing',MaxE,Ebc,Ec)
```


```{r}

# boys above poverty line
RM_PFits=Fits[,1814:1974]
RM_IFits=Fits[,1975:2025]
RM_EFits=Fits[,2026:2072]

# calculate some background info for plots
MaxP=find_furthest_nonzero(RM_PFits)
qMaxI=find_furthest_nonzero(RM_IFits)
MaxE=find_furthest_nonzero(RM_EFits)

plot_bootstraps(RM_PFits,161,expression(italic(p)),MaxP,Pbc,Pc)
plot_bootstraps(RM_IFits,51,'internalizing',MaxI,Ibc,Ic)
plot_bootstraps(RM_EFits,47,'externalizing',MaxE,Ebc,Ec)

```













```{r}
#### TEMPORAL PRECEDENCE TABLE
library(mgcv)
# load temporal precedence data from SampleConstruction.Rmd
tpdf=OutDFTmpPrec

```

```{r}
# Load the "lavaan" package
library(lavaan)


# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_totprob_r.y ~ cbcl_scr_syn_totprob_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_totprob_r.x
  cbcl_scr_syn_totprob_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_totprob_r.x
  g.y ~~ cbcl_scr_syn_totprob_r.y
  
  # Residual variances
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_totprob_r.x ~~ cbcl_scr_syn_totprob_r.x
  cbcl_scr_syn_totprob_r.y ~~ cbcl_scr_syn_totprob_r.y
'

# Fit the model to the data using maximum likelihood estimation
pfit <- sem(model, data = tpdf)

# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_internal_r.y ~ cbcl_scr_syn_internal_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_internal_r.x
  cbcl_scr_syn_internal_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_internal_r.x
  g.y ~~ cbcl_scr_syn_internal_r.y
  
  # Residual variances
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_internal_r.x ~~ cbcl_scr_syn_internal_r.x
  cbcl_scr_syn_internal_r.y ~~ cbcl_scr_syn_internal_r.y
'

# Fit the model to the data using maximum likelihood estimation
ifit <- sem(model, data = tpdf)

# Define the model syntax for the cross-lagged panel analysis
model <- '
  # Autoregressive effects
  g.y ~ g.x
  cbcl_scr_syn_external_r.y ~ cbcl_scr_syn_external_r.x
  
  # Cross-lagged effects
  g.y ~ cbcl_scr_syn_external_r.x
  cbcl_scr_syn_external_r.y ~ g.x
  
  # Residual covariances
  g.x ~~ cbcl_scr_syn_external_r.x
  g.y ~~ cbcl_scr_syn_external_r.y
  
  # Residual variances
  # note this tracks concurrent increases in outcome variables
  g.x ~~ g.x
  g.y ~~ g.y
  cbcl_scr_syn_external_r.x ~~ cbcl_scr_syn_external_r.x
  cbcl_scr_syn_external_r.y ~~ cbcl_scr_syn_external_r.y
'

# Fit the model to the data using maximum likelihood estimation
efit <- sem(model, data = tpdf)

```


